-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity swiglu_decode_mac_q6k is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    block_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    block_0_ce0 : OUT STD_LOGIC;
    block_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    block_0_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    block_0_ce1 : OUT STD_LOGIC;
    block_0_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    block_0_address2 : OUT STD_LOGIC_VECTOR (10 downto 0);
    block_0_ce2 : OUT STD_LOGIC;
    block_0_q2 : IN STD_LOGIC_VECTOR (7 downto 0);
    block_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    block_1_ce0 : OUT STD_LOGIC;
    block_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    block_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    block_1_ce1 : OUT STD_LOGIC;
    block_1_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    block_1_address2 : OUT STD_LOGIC_VECTOR (10 downto 0);
    block_1_ce2 : OUT STD_LOGIC;
    block_1_q2 : IN STD_LOGIC_VECTOR (7 downto 0);
    block_2_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    block_2_ce0 : OUT STD_LOGIC;
    block_2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    block_2_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    block_2_ce1 : OUT STD_LOGIC;
    block_2_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    block_2_address2 : OUT STD_LOGIC_VECTOR (10 downto 0);
    block_2_ce2 : OUT STD_LOGIC;
    block_2_q2 : IN STD_LOGIC_VECTOR (7 downto 0);
    block_3_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    block_3_ce0 : OUT STD_LOGIC;
    block_3_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    block_3_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    block_3_ce1 : OUT STD_LOGIC;
    block_3_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    block_3_address2 : OUT STD_LOGIC_VECTOR (10 downto 0);
    block_3_ce2 : OUT STD_LOGIC;
    block_3_q2 : IN STD_LOGIC_VECTOR (7 downto 0);
    vec_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    vec_ce0 : OUT STD_LOGIC;
    vec_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    v_base : IN STD_LOGIC_VECTOR (12 downto 0);
    idx : IN STD_LOGIC_VECTOR (12 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of swiglu_decode_mac_q6k is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (9 downto 0) := "0000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (9 downto 0) := "0000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (9 downto 0) := "0000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (9 downto 0) := "0000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (9 downto 0) := "0001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (9 downto 0) := "0010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (9 downto 0) := "0100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv13_D0 : STD_LOGIC_VECTOR (12 downto 0) := "0000011010000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv13_D1 : STD_LOGIC_VECTOR (12 downto 0) := "0000011010001";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv31_38000000 : STD_LOGIC_VECTOR (30 downto 0) := "0111000000000000000000000000000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal empty_fu_326_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_reg_699 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_fu_378_p11 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_reg_750 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_34_fu_424_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_34_reg_756 : STD_LOGIC_VECTOR (0 downto 0);
    signal sign_fu_432_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal exp_fu_440_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal exp_reg_768 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln27_1_fu_454_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln27_1_reg_773 : STD_LOGIC_VECTOR (1 downto 0);
    signal m_fu_458_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal m_reg_779 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln29_fu_493_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln29_reg_784 : STD_LOGIC_VECTOR (0 downto 0);
    signal f32_1_fu_507_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal f32_2_fu_543_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal f32_fu_576_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal d_fu_623_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal grp_decode_mac_q6k_Pipeline_VITIS_LOOP_34_1_fu_278_ap_start : STD_LOGIC;
    signal grp_decode_mac_q6k_Pipeline_VITIS_LOOP_34_1_fu_278_ap_done : STD_LOGIC;
    signal grp_decode_mac_q6k_Pipeline_VITIS_LOOP_34_1_fu_278_ap_idle : STD_LOGIC;
    signal grp_decode_mac_q6k_Pipeline_VITIS_LOOP_34_1_fu_278_ap_ready : STD_LOGIC;
    signal grp_decode_mac_q6k_Pipeline_VITIS_LOOP_34_1_fu_278_e_out : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_decode_mac_q6k_Pipeline_VITIS_LOOP_34_1_fu_278_e_out_ap_vld : STD_LOGIC;
    signal grp_decode_mac_q6k_Pipeline_VITIS_LOOP_34_1_fu_278_m_out : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_decode_mac_q6k_Pipeline_VITIS_LOOP_34_1_fu_278_m_out_ap_vld : STD_LOGIC;
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_ap_start : STD_LOGIC;
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_ap_done : STD_LOGIC;
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_ap_idle : STD_LOGIC;
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_ap_ready : STD_LOGIC;
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_0_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_0_ce0 : STD_LOGIC;
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_0_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_0_ce1 : STD_LOGIC;
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_0_address2 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_0_ce2 : STD_LOGIC;
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_1_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_1_ce0 : STD_LOGIC;
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_1_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_1_ce1 : STD_LOGIC;
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_1_address2 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_1_ce2 : STD_LOGIC;
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_2_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_2_ce0 : STD_LOGIC;
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_2_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_2_ce1 : STD_LOGIC;
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_2_address2 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_2_ce2 : STD_LOGIC;
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_3_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_3_ce0 : STD_LOGIC;
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_3_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_3_ce1 : STD_LOGIC;
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_3_address2 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_3_ce2 : STD_LOGIC;
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_vec_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_vec_ce0 : STD_LOGIC;
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_load_out_ap_vld : STD_LOGIC;
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_1_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_1_load_out_ap_vld : STD_LOGIC;
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_2_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_2_load_out_ap_vld : STD_LOGIC;
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_3_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_3_load_out_ap_vld : STD_LOGIC;
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_4_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_4_load_out_ap_vld : STD_LOGIC;
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_5_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_5_load_out_ap_vld : STD_LOGIC;
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_6_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_6_load_out_ap_vld : STD_LOGIC;
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_7_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_7_load_out_ap_vld : STD_LOGIC;
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_grp_fu_835_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_grp_fu_835_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_grp_fu_835_p_opcode : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_grp_fu_835_p_ce : STD_LOGIC;
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_grp_fu_322_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_grp_fu_322_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_grp_fu_322_p_ce : STD_LOGIC;
    signal grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_ap_start : STD_LOGIC;
    signal grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_ap_done : STD_LOGIC;
    signal grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_ap_idle : STD_LOGIC;
    signal grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_ap_ready : STD_LOGIC;
    signal grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_sum_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_sum_out_ap_vld : STD_LOGIC;
    signal grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_grp_fu_835_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_grp_fu_835_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_grp_fu_835_p_opcode : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_grp_fu_835_p_ce : STD_LOGIC;
    signal f32_4_reg_264 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_decode_mac_q6k_Pipeline_VITIS_LOOP_34_1_fu_278_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal e_loc_fu_148 : STD_LOGIC_VECTOR (8 downto 0);
    signal m_loc_fu_144 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal zext_ln107_fu_346_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln107_1_fu_370_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal block_0_ce1_local : STD_LOGIC;
    signal block_0_ce0_local : STD_LOGIC;
    signal block_1_ce1_local : STD_LOGIC;
    signal block_1_ce0_local : STD_LOGIC;
    signal block_2_ce1_local : STD_LOGIC;
    signal block_2_ce0_local : STD_LOGIC;
    signal block_3_ce1_local : STD_LOGIC;
    signal block_3_ce0_local : STD_LOGIC;
    signal grp_fu_322_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_322_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln107_fu_330_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal lshr_ln_fu_336_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln107_1_fu_354_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal lshr_ln107_1_fu_360_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_fu_378_p9 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_s_fu_401_p9 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_s_fu_401_p11 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln27_fu_450_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_3_fu_473_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_ln29_fu_467_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_4_fu_483_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp1_fu_532_p5 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_35_fu_524_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln39_1_fu_549_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal zext_ln39_fu_556_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal add_ln39_fu_560_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_2_fu_566_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_322_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_322_ce : STD_LOGIC;
    signal grp_fu_835_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_835_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_835_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_835_ce : STD_LOGIC;
    signal ap_return_preg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal tmp_fu_378_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_378_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_378_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_378_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_401_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_401_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_401_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_401_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component swiglu_decode_mac_q6k_Pipeline_VITIS_LOOP_34_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        zext_ln27 : IN STD_LOGIC_VECTOR (9 downto 0);
        e_out : OUT STD_LOGIC_VECTOR (8 downto 0);
        e_out_ap_vld : OUT STD_LOGIC;
        m_out : OUT STD_LOGIC_VECTOR (8 downto 0);
        m_out_ap_vld : OUT STD_LOGIC );
    end component;


    component swiglu_decode_mac_q6k_Pipeline_MAC_Q6K IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        idx : IN STD_LOGIC_VECTOR (12 downto 0);
        block_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        block_0_ce0 : OUT STD_LOGIC;
        block_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        block_0_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        block_0_ce1 : OUT STD_LOGIC;
        block_0_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
        block_0_address2 : OUT STD_LOGIC_VECTOR (10 downto 0);
        block_0_ce2 : OUT STD_LOGIC;
        block_0_q2 : IN STD_LOGIC_VECTOR (7 downto 0);
        block_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        block_1_ce0 : OUT STD_LOGIC;
        block_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        block_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        block_1_ce1 : OUT STD_LOGIC;
        block_1_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
        block_1_address2 : OUT STD_LOGIC_VECTOR (10 downto 0);
        block_1_ce2 : OUT STD_LOGIC;
        block_1_q2 : IN STD_LOGIC_VECTOR (7 downto 0);
        block_2_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        block_2_ce0 : OUT STD_LOGIC;
        block_2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        block_2_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        block_2_ce1 : OUT STD_LOGIC;
        block_2_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
        block_2_address2 : OUT STD_LOGIC_VECTOR (10 downto 0);
        block_2_ce2 : OUT STD_LOGIC;
        block_2_q2 : IN STD_LOGIC_VECTOR (7 downto 0);
        block_3_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        block_3_ce0 : OUT STD_LOGIC;
        block_3_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        block_3_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        block_3_ce1 : OUT STD_LOGIC;
        block_3_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
        block_3_address2 : OUT STD_LOGIC_VECTOR (10 downto 0);
        block_3_ce2 : OUT STD_LOGIC;
        block_3_q2 : IN STD_LOGIC_VECTOR (7 downto 0);
        v_base : IN STD_LOGIC_VECTOR (12 downto 0);
        vec_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        vec_ce0 : OUT STD_LOGIC;
        vec_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_load_out_ap_vld : OUT STD_LOGIC;
        acc_1_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_1_load_out_ap_vld : OUT STD_LOGIC;
        acc_2_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_2_load_out_ap_vld : OUT STD_LOGIC;
        acc_3_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_3_load_out_ap_vld : OUT STD_LOGIC;
        acc_4_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_4_load_out_ap_vld : OUT STD_LOGIC;
        acc_5_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_5_load_out_ap_vld : OUT STD_LOGIC;
        acc_6_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_6_load_out_ap_vld : OUT STD_LOGIC;
        acc_7_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_7_load_out_ap_vld : OUT STD_LOGIC;
        grp_fu_835_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_835_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_835_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
        grp_fu_835_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_835_p_ce : OUT STD_LOGIC;
        grp_fu_322_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_322_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_322_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_322_p_ce : OUT STD_LOGIC );
    end component;


    component swiglu_decode_mac_q6k_Pipeline_REDUCE_Q6K IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        acc_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_1_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_2_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_3_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_4_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_5_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_6_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_7_load_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        sum_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        sum_out_ap_vld : OUT STD_LOGIC;
        grp_fu_835_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_835_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_835_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
        grp_fu_835_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_835_p_ce : OUT STD_LOGIC );
    end component;


    component swiglu_fmul_32ns_32ns_32_3_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component swiglu_sparsemux_9_2_8_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (1 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (7 downto 0);
        def : IN STD_LOGIC_VECTOR (7 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component swiglu_sparsemux_9_2_8_1_1_x IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (1 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (7 downto 0);
        def : IN STD_LOGIC_VECTOR (7 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component swiglu_fadd_32ns_32ns_32_4_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    grp_decode_mac_q6k_Pipeline_VITIS_LOOP_34_1_fu_278 : component swiglu_decode_mac_q6k_Pipeline_VITIS_LOOP_34_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_decode_mac_q6k_Pipeline_VITIS_LOOP_34_1_fu_278_ap_start,
        ap_done => grp_decode_mac_q6k_Pipeline_VITIS_LOOP_34_1_fu_278_ap_done,
        ap_idle => grp_decode_mac_q6k_Pipeline_VITIS_LOOP_34_1_fu_278_ap_idle,
        ap_ready => grp_decode_mac_q6k_Pipeline_VITIS_LOOP_34_1_fu_278_ap_ready,
        zext_ln27 => m_reg_779,
        e_out => grp_decode_mac_q6k_Pipeline_VITIS_LOOP_34_1_fu_278_e_out,
        e_out_ap_vld => grp_decode_mac_q6k_Pipeline_VITIS_LOOP_34_1_fu_278_e_out_ap_vld,
        m_out => grp_decode_mac_q6k_Pipeline_VITIS_LOOP_34_1_fu_278_m_out,
        m_out_ap_vld => grp_decode_mac_q6k_Pipeline_VITIS_LOOP_34_1_fu_278_m_out_ap_vld);

    grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285 : component swiglu_decode_mac_q6k_Pipeline_MAC_Q6K
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_ap_start,
        ap_done => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_ap_done,
        ap_idle => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_ap_idle,
        ap_ready => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_ap_ready,
        idx => idx,
        block_0_address0 => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_0_address0,
        block_0_ce0 => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_0_ce0,
        block_0_q0 => block_0_q0,
        block_0_address1 => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_0_address1,
        block_0_ce1 => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_0_ce1,
        block_0_q1 => block_0_q1,
        block_0_address2 => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_0_address2,
        block_0_ce2 => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_0_ce2,
        block_0_q2 => block_0_q2,
        block_1_address0 => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_1_address0,
        block_1_ce0 => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_1_ce0,
        block_1_q0 => block_1_q0,
        block_1_address1 => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_1_address1,
        block_1_ce1 => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_1_ce1,
        block_1_q1 => block_1_q1,
        block_1_address2 => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_1_address2,
        block_1_ce2 => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_1_ce2,
        block_1_q2 => block_1_q2,
        block_2_address0 => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_2_address0,
        block_2_ce0 => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_2_ce0,
        block_2_q0 => block_2_q0,
        block_2_address1 => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_2_address1,
        block_2_ce1 => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_2_ce1,
        block_2_q1 => block_2_q1,
        block_2_address2 => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_2_address2,
        block_2_ce2 => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_2_ce2,
        block_2_q2 => block_2_q2,
        block_3_address0 => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_3_address0,
        block_3_ce0 => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_3_ce0,
        block_3_q0 => block_3_q0,
        block_3_address1 => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_3_address1,
        block_3_ce1 => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_3_ce1,
        block_3_q1 => block_3_q1,
        block_3_address2 => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_3_address2,
        block_3_ce2 => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_3_ce2,
        block_3_q2 => block_3_q2,
        v_base => v_base,
        vec_address0 => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_vec_address0,
        vec_ce0 => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_vec_ce0,
        vec_q0 => vec_q0,
        acc_load_out => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_load_out,
        acc_load_out_ap_vld => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_load_out_ap_vld,
        acc_1_load_out => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_1_load_out,
        acc_1_load_out_ap_vld => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_1_load_out_ap_vld,
        acc_2_load_out => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_2_load_out,
        acc_2_load_out_ap_vld => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_2_load_out_ap_vld,
        acc_3_load_out => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_3_load_out,
        acc_3_load_out_ap_vld => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_3_load_out_ap_vld,
        acc_4_load_out => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_4_load_out,
        acc_4_load_out_ap_vld => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_4_load_out_ap_vld,
        acc_5_load_out => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_5_load_out,
        acc_5_load_out_ap_vld => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_5_load_out_ap_vld,
        acc_6_load_out => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_6_load_out,
        acc_6_load_out_ap_vld => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_6_load_out_ap_vld,
        acc_7_load_out => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_7_load_out,
        acc_7_load_out_ap_vld => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_7_load_out_ap_vld,
        grp_fu_835_p_din0 => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_grp_fu_835_p_din0,
        grp_fu_835_p_din1 => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_grp_fu_835_p_din1,
        grp_fu_835_p_opcode => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_grp_fu_835_p_opcode,
        grp_fu_835_p_dout0 => grp_fu_835_p2,
        grp_fu_835_p_ce => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_grp_fu_835_p_ce,
        grp_fu_322_p_din0 => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_grp_fu_322_p_din0,
        grp_fu_322_p_din1 => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_grp_fu_322_p_din1,
        grp_fu_322_p_dout0 => grp_fu_322_p2,
        grp_fu_322_p_ce => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_grp_fu_322_p_ce);

    grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309 : component swiglu_decode_mac_q6k_Pipeline_REDUCE_Q6K
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_ap_start,
        ap_done => grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_ap_done,
        ap_idle => grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_ap_idle,
        ap_ready => grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_ap_ready,
        acc_load_reload => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_load_out,
        acc_1_load_reload => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_1_load_out,
        acc_2_load_reload => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_2_load_out,
        acc_3_load_reload => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_3_load_out,
        acc_4_load_reload => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_4_load_out,
        acc_5_load_reload => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_5_load_out,
        acc_6_load_reload => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_6_load_out,
        acc_7_load_reload => grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_acc_7_load_out,
        sum_out => grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_sum_out,
        sum_out_ap_vld => grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_sum_out_ap_vld,
        grp_fu_835_p_din0 => grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_grp_fu_835_p_din0,
        grp_fu_835_p_din1 => grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_grp_fu_835_p_din1,
        grp_fu_835_p_opcode => grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_grp_fu_835_p_opcode,
        grp_fu_835_p_dout0 => grp_fu_835_p2,
        grp_fu_835_p_ce => grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_grp_fu_835_p_ce);

    fmul_32ns_32ns_32_3_max_dsp_1_U187 : component swiglu_fmul_32ns_32ns_32_3_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_322_p0,
        din1 => grp_fu_322_p1,
        ce => grp_fu_322_ce,
        dout => grp_fu_322_p2);

    sparsemux_9_2_8_1_1_U188 : component swiglu_sparsemux_9_2_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 8,
        CASE1 => "01",
        din1_WIDTH => 8,
        CASE2 => "10",
        din2_WIDTH => 8,
        CASE3 => "11",
        din3_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => block_0_q1,
        din1 => block_1_q1,
        din2 => block_2_q1,
        din3 => block_3_q1,
        def => tmp_fu_378_p9,
        sel => empty_reg_699,
        dout => tmp_fu_378_p11);

    sparsemux_9_2_8_1_1_x_U189 : component swiglu_sparsemux_9_2_8_1_1_x
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "11",
        din0_WIDTH => 8,
        CASE1 => "00",
        din1_WIDTH => 8,
        CASE2 => "01",
        din2_WIDTH => 8,
        CASE3 => "10",
        din3_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => block_0_q0,
        din1 => block_1_q0,
        din2 => block_2_q0,
        din3 => block_3_q0,
        def => tmp_s_fu_401_p9,
        sel => empty_reg_699,
        dout => tmp_s_fu_401_p11);

    fadd_32ns_32ns_32_4_full_dsp_1_U190 : component swiglu_fadd_32ns_32ns_32_4_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_835_p0,
        din1 => grp_fu_835_p1,
        ce => grp_fu_835_ce,
        dout => grp_fu_835_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_return_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_preg <= ap_const_lv32_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
                    ap_return_preg <= grp_fu_322_p2;
                end if; 
            end if;
        end if;
    end process;


    grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_ap_ready = ap_const_logic_1)) then 
                    grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_ap_ready = ap_const_logic_1)) then 
                    grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_decode_mac_q6k_Pipeline_VITIS_LOOP_34_1_fu_278_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_decode_mac_q6k_Pipeline_VITIS_LOOP_34_1_fu_278_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln29_fu_493_p2 = ap_const_lv1_0) and (exp_fu_440_p4 = ap_const_lv5_0))) then 
                    grp_decode_mac_q6k_Pipeline_VITIS_LOOP_34_1_fu_278_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_decode_mac_q6k_Pipeline_VITIS_LOOP_34_1_fu_278_ap_ready = ap_const_logic_1)) then 
                    grp_decode_mac_q6k_Pipeline_VITIS_LOOP_34_1_fu_278_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    f32_4_reg_264_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln29_fu_493_p2 = ap_const_lv1_1))) then 
                                f32_4_reg_264(31 downto 13) <= sign_fu_432_p3(31 downto 13);
            elsif ((not((exp_reg_768 = ap_const_lv5_1F)) and not((exp_reg_768 = ap_const_lv5_0)) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln29_reg_784 = ap_const_lv1_0))) then 
                                f32_4_reg_264(31 downto 13) <= f32_fu_576_p6(31 downto 13);
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln29_reg_784 = ap_const_lv1_0) and (exp_reg_768 = ap_const_lv5_1F))) then 
                                f32_4_reg_264(31 downto 13) <= f32_1_fu_507_p6(31 downto 13);
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln29_reg_784 = ap_const_lv1_0) and (exp_reg_768 = ap_const_lv5_0))) then 
                                f32_4_reg_264(31 downto 13) <= f32_2_fu_543_p2(31 downto 13);
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_decode_mac_q6k_Pipeline_VITIS_LOOP_34_1_fu_278_e_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                e_loc_fu_148 <= grp_decode_mac_q6k_Pipeline_VITIS_LOOP_34_1_fu_278_e_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                empty_reg_699 <= empty_fu_326_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                exp_reg_768 <= tmp_s_fu_401_p11(6 downto 2);
                icmp_ln29_reg_784 <= icmp_ln29_fu_493_p2;
                m_reg_779 <= m_fu_458_p3;
                tmp_34_reg_756 <= tmp_s_fu_401_p11(7 downto 7);
                tmp_reg_750 <= tmp_fu_378_p11;
                trunc_ln27_1_reg_773 <= trunc_ln27_1_fu_454_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_decode_mac_q6k_Pipeline_VITIS_LOOP_34_1_fu_278_m_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                m_loc_fu_144 <= grp_decode_mac_q6k_Pipeline_VITIS_LOOP_34_1_fu_278_m_out;
            end if;
        end if;
    end process;
    f32_4_reg_264(12 downto 0) <= "0000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, exp_fu_440_p4, icmp_ln29_fu_493_p2, grp_decode_mac_q6k_Pipeline_VITIS_LOOP_34_1_fu_278_ap_done, grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_ap_done, grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_ap_done, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln29_fu_493_p2 = ap_const_lv1_0) and (exp_fu_440_p4 = ap_const_lv5_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state4 => 
                if (((grp_decode_mac_q6k_Pipeline_VITIS_LOOP_34_1_fu_278_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXX";
        end case;
    end process;
    add_ln107_1_fu_354_p2 <= std_logic_vector(unsigned(idx) + unsigned(ap_const_lv13_D1));
    add_ln107_fu_330_p2 <= std_logic_vector(unsigned(idx) + unsigned(ap_const_lv13_D0));
    add_ln39_fu_560_p2 <= std_logic_vector(unsigned(zext_ln39_fu_556_p1) + unsigned(ap_const_lv31_38000000));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_decode_mac_q6k_Pipeline_VITIS_LOOP_34_1_fu_278_ap_done)
    begin
        if ((grp_decode_mac_q6k_Pipeline_VITIS_LOOP_34_1_fu_278_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_ap_done)
    begin
        if ((grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_fsm_state7_blk_assign_proc : process(grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_ap_done)
    begin
        if ((grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_assign_proc : process(grp_fu_322_p2, ap_return_preg, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            ap_return <= grp_fu_322_p2;
        else 
            ap_return <= ap_return_preg;
        end if; 
    end process;


    block_0_address0_assign_proc : process(grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_0_address0, ap_CS_fsm_state5, zext_ln107_1_fu_370_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            block_0_address0 <= grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_0_address0;
        else 
            block_0_address0 <= zext_ln107_1_fu_370_p1(11 - 1 downto 0);
        end if; 
    end process;


    block_0_address1_assign_proc : process(grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_0_address1, ap_CS_fsm_state5, zext_ln107_fu_346_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            block_0_address1 <= grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_0_address1;
        else 
            block_0_address1 <= zext_ln107_fu_346_p1(11 - 1 downto 0);
        end if; 
    end process;

    block_0_address2 <= grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_0_address2;

    block_0_ce0_assign_proc : process(grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_0_ce0, ap_CS_fsm_state5, block_0_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            block_0_ce0 <= grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_0_ce0;
        else 
            block_0_ce0 <= block_0_ce0_local;
        end if; 
    end process;


    block_0_ce0_local_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            block_0_ce0_local <= ap_const_logic_1;
        else 
            block_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    block_0_ce1_assign_proc : process(grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_0_ce1, ap_CS_fsm_state5, block_0_ce1_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            block_0_ce1 <= grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_0_ce1;
        else 
            block_0_ce1 <= block_0_ce1_local;
        end if; 
    end process;


    block_0_ce1_local_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            block_0_ce1_local <= ap_const_logic_1;
        else 
            block_0_ce1_local <= ap_const_logic_0;
        end if; 
    end process;


    block_0_ce2_assign_proc : process(grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_0_ce2, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            block_0_ce2 <= grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_0_ce2;
        else 
            block_0_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    block_1_address0_assign_proc : process(grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_1_address0, ap_CS_fsm_state5, zext_ln107_1_fu_370_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            block_1_address0 <= grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_1_address0;
        else 
            block_1_address0 <= zext_ln107_1_fu_370_p1(11 - 1 downto 0);
        end if; 
    end process;


    block_1_address1_assign_proc : process(grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_1_address1, ap_CS_fsm_state5, zext_ln107_fu_346_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            block_1_address1 <= grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_1_address1;
        else 
            block_1_address1 <= zext_ln107_fu_346_p1(11 - 1 downto 0);
        end if; 
    end process;

    block_1_address2 <= grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_1_address2;

    block_1_ce0_assign_proc : process(grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_1_ce0, ap_CS_fsm_state5, block_1_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            block_1_ce0 <= grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_1_ce0;
        else 
            block_1_ce0 <= block_1_ce0_local;
        end if; 
    end process;


    block_1_ce0_local_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            block_1_ce0_local <= ap_const_logic_1;
        else 
            block_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    block_1_ce1_assign_proc : process(grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_1_ce1, ap_CS_fsm_state5, block_1_ce1_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            block_1_ce1 <= grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_1_ce1;
        else 
            block_1_ce1 <= block_1_ce1_local;
        end if; 
    end process;


    block_1_ce1_local_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            block_1_ce1_local <= ap_const_logic_1;
        else 
            block_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;


    block_1_ce2_assign_proc : process(grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_1_ce2, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            block_1_ce2 <= grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_1_ce2;
        else 
            block_1_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    block_2_address0_assign_proc : process(grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_2_address0, ap_CS_fsm_state5, zext_ln107_1_fu_370_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            block_2_address0 <= grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_2_address0;
        else 
            block_2_address0 <= zext_ln107_1_fu_370_p1(11 - 1 downto 0);
        end if; 
    end process;


    block_2_address1_assign_proc : process(grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_2_address1, ap_CS_fsm_state5, zext_ln107_fu_346_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            block_2_address1 <= grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_2_address1;
        else 
            block_2_address1 <= zext_ln107_fu_346_p1(11 - 1 downto 0);
        end if; 
    end process;

    block_2_address2 <= grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_2_address2;

    block_2_ce0_assign_proc : process(grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_2_ce0, ap_CS_fsm_state5, block_2_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            block_2_ce0 <= grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_2_ce0;
        else 
            block_2_ce0 <= block_2_ce0_local;
        end if; 
    end process;


    block_2_ce0_local_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            block_2_ce0_local <= ap_const_logic_1;
        else 
            block_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    block_2_ce1_assign_proc : process(grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_2_ce1, ap_CS_fsm_state5, block_2_ce1_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            block_2_ce1 <= grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_2_ce1;
        else 
            block_2_ce1 <= block_2_ce1_local;
        end if; 
    end process;


    block_2_ce1_local_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            block_2_ce1_local <= ap_const_logic_1;
        else 
            block_2_ce1_local <= ap_const_logic_0;
        end if; 
    end process;


    block_2_ce2_assign_proc : process(grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_2_ce2, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            block_2_ce2 <= grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_2_ce2;
        else 
            block_2_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    block_3_address0_assign_proc : process(grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_3_address0, ap_CS_fsm_state5, zext_ln107_1_fu_370_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            block_3_address0 <= grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_3_address0;
        else 
            block_3_address0 <= zext_ln107_1_fu_370_p1(11 - 1 downto 0);
        end if; 
    end process;


    block_3_address1_assign_proc : process(grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_3_address1, ap_CS_fsm_state5, zext_ln107_fu_346_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            block_3_address1 <= grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_3_address1;
        else 
            block_3_address1 <= zext_ln107_fu_346_p1(11 - 1 downto 0);
        end if; 
    end process;

    block_3_address2 <= grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_3_address2;

    block_3_ce0_assign_proc : process(grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_3_ce0, ap_CS_fsm_state5, block_3_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            block_3_ce0 <= grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_3_ce0;
        else 
            block_3_ce0 <= block_3_ce0_local;
        end if; 
    end process;


    block_3_ce0_local_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            block_3_ce0_local <= ap_const_logic_1;
        else 
            block_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    block_3_ce1_assign_proc : process(grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_3_ce1, ap_CS_fsm_state5, block_3_ce1_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            block_3_ce1 <= grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_3_ce1;
        else 
            block_3_ce1 <= block_3_ce1_local;
        end if; 
    end process;


    block_3_ce1_local_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            block_3_ce1_local <= ap_const_logic_1;
        else 
            block_3_ce1_local <= ap_const_logic_0;
        end if; 
    end process;


    block_3_ce2_assign_proc : process(grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_3_ce2, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            block_3_ce2 <= grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_block_3_ce2;
        else 
            block_3_ce2 <= ap_const_logic_0;
        end if; 
    end process;

    d_fu_623_p1 <= f32_4_reg_264;
    empty_fu_326_p1 <= idx(2 - 1 downto 0);
    exp_fu_440_p4 <= tmp_s_fu_401_p11(6 downto 2);
    f32_1_fu_507_p6 <= ((((tmp_34_reg_756 & ap_const_lv8_FF) & trunc_ln27_1_reg_773) & tmp_reg_750) & ap_const_lv13_0);
    f32_2_fu_543_p2 <= (tmp_35_fu_524_p3 or tmp1_fu_532_p5);
    f32_fu_576_p6 <= ((((tmp_34_reg_756 & tmp_2_fu_566_p4) & trunc_ln27_1_reg_773) & tmp_reg_750) & ap_const_lv13_0);
    grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_ap_start <= grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_ap_start_reg;
    grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_ap_start <= grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_ap_start_reg;
    grp_decode_mac_q6k_Pipeline_VITIS_LOOP_34_1_fu_278_ap_start <= grp_decode_mac_q6k_Pipeline_VITIS_LOOP_34_1_fu_278_ap_start_reg;

    grp_fu_322_ce_assign_proc : process(grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_grp_fu_322_p_ce, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_fu_322_ce <= grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_grp_fu_322_p_ce;
        else 
            grp_fu_322_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_322_p0_assign_proc : process(d_fu_623_p1, ap_CS_fsm_state8, grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_grp_fu_322_p_din0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_fu_322_p0 <= grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_grp_fu_322_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            grp_fu_322_p0 <= d_fu_623_p1;
        else 
            grp_fu_322_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_322_p1_assign_proc : process(ap_CS_fsm_state8, grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_grp_fu_322_p_din1, grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_sum_out, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_fu_322_p1 <= grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_grp_fu_322_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            grp_fu_322_p1 <= grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_sum_out;
        else 
            grp_fu_322_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_835_ce_assign_proc : process(grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_grp_fu_835_p_ce, grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_grp_fu_835_p_ce, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            grp_fu_835_ce <= grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_grp_fu_835_p_ce;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_fu_835_ce <= grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_grp_fu_835_p_ce;
        else 
            grp_fu_835_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_835_p0_assign_proc : process(grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_grp_fu_835_p_din0, grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_grp_fu_835_p_din0, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            grp_fu_835_p0 <= grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_grp_fu_835_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_fu_835_p0 <= grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_grp_fu_835_p_din0;
        else 
            grp_fu_835_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_835_p1_assign_proc : process(grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_grp_fu_835_p_din1, grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_grp_fu_835_p_din1, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            grp_fu_835_p1 <= grp_decode_mac_q6k_Pipeline_REDUCE_Q6K_fu_309_grp_fu_835_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_fu_835_p1 <= grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_grp_fu_835_p_din1;
        else 
            grp_fu_835_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    icmp_ln29_fu_493_p2 <= "1" when (tmp_4_fu_483_p4 = ap_const_lv10_0) else "0";
    lshr_ln107_1_fu_360_p4 <= add_ln107_1_fu_354_p2(12 downto 2);
    lshr_ln_fu_336_p4 <= add_ln107_fu_330_p2(12 downto 2);
    m_fu_458_p3 <= (trunc_ln27_1_fu_454_p1 & tmp_fu_378_p11);
    or_ln29_fu_467_p2 <= (trunc_ln27_fu_450_p1 or exp_fu_440_p4);
    shl_ln39_1_fu_549_p3 <= (exp_reg_768 & ap_const_lv23_0);
    sign_fu_432_p3 <= (tmp_34_fu_424_p3 & ap_const_lv31_0);
    tmp1_fu_532_p5 <= (((tmp_34_reg_756 & ap_const_lv8_0) & m_loc_fu_144) & ap_const_lv14_0);
    tmp_2_fu_566_p4 <= add_ln39_fu_560_p2(30 downto 23);
    tmp_34_fu_424_p3 <= tmp_s_fu_401_p11(7 downto 7);
    tmp_35_fu_524_p3 <= (e_loc_fu_148 & ap_const_lv23_0);
    tmp_3_fu_473_p4 <= tmp_fu_378_p11(7 downto 5);
    tmp_4_fu_483_p4 <= ((trunc_ln27_1_fu_454_p1 & tmp_3_fu_473_p4) & or_ln29_fu_467_p2);
    tmp_fu_378_p9 <= "XXXXXXXX";
    tmp_s_fu_401_p9 <= "XXXXXXXX";
    trunc_ln27_1_fu_454_p1 <= tmp_s_fu_401_p11(2 - 1 downto 0);
    trunc_ln27_fu_450_p1 <= tmp_fu_378_p11(5 - 1 downto 0);
    vec_address0 <= grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_vec_address0;
    vec_ce0 <= grp_decode_mac_q6k_Pipeline_MAC_Q6K_fu_285_vec_ce0;
    zext_ln107_1_fu_370_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln107_1_fu_360_p4),64));
    zext_ln107_fu_346_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_336_p4),64));
    zext_ln39_fu_556_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln39_1_fu_549_p3),31));
end behav;
