-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity swiglu_swiglu_Pipeline_5 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    W_down_load : IN STD_LOGIC_VECTOR (7 downto 0);
    row_buf_11_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    row_buf_11_ce0 : OUT STD_LOGIC;
    row_buf_11_we0 : OUT STD_LOGIC;
    row_buf_11_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    row_buf_10_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    row_buf_10_ce0 : OUT STD_LOGIC;
    row_buf_10_we0 : OUT STD_LOGIC;
    row_buf_10_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    row_buf_9_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    row_buf_9_ce0 : OUT STD_LOGIC;
    row_buf_9_we0 : OUT STD_LOGIC;
    row_buf_9_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    row_buf_8_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    row_buf_8_ce0 : OUT STD_LOGIC;
    row_buf_8_we0 : OUT STD_LOGIC;
    row_buf_8_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of swiglu_swiglu_Pipeline_5 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv13_1200 : STD_LOGIC_VECTOR (12 downto 0) := "1001000000000";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal exitcond22_fu_120_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal p_cast11_fu_146_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal loop_index17_fu_46 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    signal empty_fu_126_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_loop_index17_load : STD_LOGIC_VECTOR (12 downto 0);
    signal row_buf_10_we0_local : STD_LOGIC;
    signal empty_50_fu_132_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal row_buf_10_ce0_local : STD_LOGIC;
    signal row_buf_9_we0_local : STD_LOGIC;
    signal row_buf_9_ce0_local : STD_LOGIC;
    signal row_buf_8_we0_local : STD_LOGIC;
    signal row_buf_8_ce0_local : STD_LOGIC;
    signal row_buf_11_we0_local : STD_LOGIC;
    signal row_buf_11_ce0_local : STD_LOGIC;
    signal tmp_s_fu_136_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component swiglu_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component swiglu_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    loop_index17_fu_46_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if ((exitcond22_fu_120_p2 = ap_const_lv1_0)) then 
                    loop_index17_fu_46 <= empty_fu_126_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    loop_index17_fu_46 <= ap_const_lv13_0;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1_pp0_stage0_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start_int = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, exitcond22_fu_120_p2)
    begin
        if (((exitcond22_fu_120_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_loop_index17_load_assign_proc : process(ap_CS_fsm_state1, loop_index17_fu_46, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_loop_index17_load <= ap_const_lv13_0;
        else 
            ap_sig_allocacmp_loop_index17_load <= loop_index17_fu_46;
        end if; 
    end process;

    empty_50_fu_132_p1 <= ap_sig_allocacmp_loop_index17_load(2 - 1 downto 0);
    empty_fu_126_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_loop_index17_load) + unsigned(ap_const_lv13_1));
    exitcond22_fu_120_p2 <= "1" when (ap_sig_allocacmp_loop_index17_load = ap_const_lv13_1200) else "0";
    p_cast11_fu_146_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_136_p4),64));
    row_buf_10_address0 <= p_cast11_fu_146_p1(11 - 1 downto 0);
    row_buf_10_ce0 <= row_buf_10_ce0_local;

    row_buf_10_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            row_buf_10_ce0_local <= ap_const_logic_1;
        else 
            row_buf_10_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    row_buf_10_d0 <= W_down_load;
    row_buf_10_we0 <= row_buf_10_we0_local;

    row_buf_10_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, exitcond22_fu_120_p2, empty_50_fu_132_p1)
    begin
        if (((empty_50_fu_132_p1 = ap_const_lv2_2) and (exitcond22_fu_120_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            row_buf_10_we0_local <= ap_const_logic_1;
        else 
            row_buf_10_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    row_buf_11_address0 <= p_cast11_fu_146_p1(11 - 1 downto 0);
    row_buf_11_ce0 <= row_buf_11_ce0_local;

    row_buf_11_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            row_buf_11_ce0_local <= ap_const_logic_1;
        else 
            row_buf_11_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    row_buf_11_d0 <= W_down_load;
    row_buf_11_we0 <= row_buf_11_we0_local;

    row_buf_11_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, exitcond22_fu_120_p2, empty_50_fu_132_p1)
    begin
        if (((empty_50_fu_132_p1 = ap_const_lv2_3) and (exitcond22_fu_120_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            row_buf_11_we0_local <= ap_const_logic_1;
        else 
            row_buf_11_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    row_buf_8_address0 <= p_cast11_fu_146_p1(11 - 1 downto 0);
    row_buf_8_ce0 <= row_buf_8_ce0_local;

    row_buf_8_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            row_buf_8_ce0_local <= ap_const_logic_1;
        else 
            row_buf_8_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    row_buf_8_d0 <= W_down_load;
    row_buf_8_we0 <= row_buf_8_we0_local;

    row_buf_8_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, exitcond22_fu_120_p2, empty_50_fu_132_p1)
    begin
        if (((empty_50_fu_132_p1 = ap_const_lv2_0) and (exitcond22_fu_120_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            row_buf_8_we0_local <= ap_const_logic_1;
        else 
            row_buf_8_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    row_buf_9_address0 <= p_cast11_fu_146_p1(11 - 1 downto 0);
    row_buf_9_ce0 <= row_buf_9_ce0_local;

    row_buf_9_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            row_buf_9_ce0_local <= ap_const_logic_1;
        else 
            row_buf_9_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    row_buf_9_d0 <= W_down_load;
    row_buf_9_we0 <= row_buf_9_we0_local;

    row_buf_9_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, exitcond22_fu_120_p2, empty_50_fu_132_p1)
    begin
        if (((empty_50_fu_132_p1 = ap_const_lv2_1) and (exitcond22_fu_120_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            row_buf_9_we0_local <= ap_const_logic_1;
        else 
            row_buf_9_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    tmp_s_fu_136_p4 <= ap_sig_allocacmp_loop_index17_load(12 downto 2);
end behav;
