-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity swiglu_swiglu_Pipeline_DECODE_MAC4 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    block_buf_a_8_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    block_buf_a_8_ce0 : OUT STD_LOGIC;
    block_buf_a_8_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    block_buf_a_9_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    block_buf_a_9_ce0 : OUT STD_LOGIC;
    block_buf_a_9_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    block_buf_a_10_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    block_buf_a_10_ce0 : OUT STD_LOGIC;
    block_buf_a_10_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    block_buf_a_11_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    block_buf_a_11_ce0 : OUT STD_LOGIC;
    block_buf_a_11_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    empty_32 : IN STD_LOGIC_VECTOR (5 downto 0);
    empty_33 : IN STD_LOGIC_VECTOR (5 downto 0);
    empty_34 : IN STD_LOGIC_VECTOR (5 downto 0);
    empty_35 : IN STD_LOGIC_VECTOR (5 downto 0);
    sc6_36 : IN STD_LOGIC_VECTOR (5 downto 0);
    sc6_31 : IN STD_LOGIC_VECTOR (5 downto 0);
    sc6_37 : IN STD_LOGIC_VECTOR (5 downto 0);
    sc6_38 : IN STD_LOGIC_VECTOR (5 downto 0);
    empty_36 : IN STD_LOGIC_VECTOR (5 downto 0);
    empty_37 : IN STD_LOGIC_VECTOR (5 downto 0);
    empty_38 : IN STD_LOGIC_VECTOR (5 downto 0);
    empty : IN STD_LOGIC_VECTOR (5 downto 0);
    mn6_35 : IN STD_LOGIC_VECTOR (5 downto 0);
    mn6_36 : IN STD_LOGIC_VECTOR (5 downto 0);
    mn6_37 : IN STD_LOGIC_VECTOR (5 downto 0);
    mn6_38 : IN STD_LOGIC_VECTOR (5 downto 0);
    b_2 : IN STD_LOGIC_VECTOR (4 downto 0);
    gate_cache_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    gate_cache_ce0 : OUT STD_LOGIC;
    gate_cache_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_w_32_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_w_32_load_out_ap_vld : OUT STD_LOGIC;
    acc_w_33_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_w_33_load_out_ap_vld : OUT STD_LOGIC;
    acc_w_34_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_w_34_load_out_ap_vld : OUT STD_LOGIC;
    acc_w_35_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_w_35_load_out_ap_vld : OUT STD_LOGIC;
    acc_w_36_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_w_36_load_out_ap_vld : OUT STD_LOGIC;
    acc_w_37_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_w_37_load_out_ap_vld : OUT STD_LOGIC;
    acc_w_38_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_w_38_load_out_ap_vld : OUT STD_LOGIC;
    acc_w_39_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_w_39_load_out_ap_vld : OUT STD_LOGIC;
    acc_m_32_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_m_32_load_out_ap_vld : OUT STD_LOGIC;
    acc_m_33_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_m_33_load_out_ap_vld : OUT STD_LOGIC;
    acc_m_34_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_m_34_load_out_ap_vld : OUT STD_LOGIC;
    acc_m_35_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_m_35_load_out_ap_vld : OUT STD_LOGIC;
    acc_m_36_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_m_36_load_out_ap_vld : OUT STD_LOGIC;
    acc_m_37_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_m_37_load_out_ap_vld : OUT STD_LOGIC;
    acc_m_38_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_m_38_load_out_ap_vld : OUT STD_LOGIC;
    acc_m_39_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_m_39_load_out_ap_vld : OUT STD_LOGIC;
    grp_fu_16169_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16169_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16169_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_16169_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16169_p_ce : OUT STD_LOGIC;
    grp_fu_16173_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16173_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16173_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_16173_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16173_p_ce : OUT STD_LOGIC;
    grp_fu_2386_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2386_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2386_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2386_p_ce : OUT STD_LOGIC;
    grp_fu_2390_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2390_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2390_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2390_p_ce : OUT STD_LOGIC;
    grp_fu_16177_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16177_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16177_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16177_p_ce : OUT STD_LOGIC;
    grp_fu_16181_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16181_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16181_p_ce : OUT STD_LOGIC;
    grp_fu_16184_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16184_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16184_p_ce : OUT STD_LOGIC;
    grp_fu_16187_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16187_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16187_p_ce : OUT STD_LOGIC );
end;


architecture behav of swiglu_swiglu_Pipeline_DECODE_MAC4 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv9_100 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv6_4 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln126_fu_642_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal n_reg_1363 : STD_LOGIC_VECTOR (8 downto 0);
    signal n_reg_1363_pp0_iter1_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal n_reg_1363_pp0_iter2_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln126_reg_1372 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln126_reg_1372_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln126_reg_1372_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln126_reg_1372_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln126_reg_1372_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln126_reg_1372_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln126_reg_1372_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln126_reg_1372_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln126_reg_1372_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln126_reg_1372_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln126_reg_1372_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln126_reg_1372_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln126_reg_1372_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln129_5_reg_1396 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln129_5_reg_1396_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln129_5_reg_1396_pp0_iter3_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal nibble_fu_750_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal nibble_reg_1401 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_15_fu_754_p19 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_15_reg_1406 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln133_fu_786_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln135_fu_790_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln129_fu_794_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln129_reg_1421 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln129_reg_1421_pp0_iter4_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln129_reg_1421_pp0_iter5_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln129_reg_1421_pp0_iter6_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln129_reg_1421_pp0_iter7_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln129_reg_1421_pp0_iter8_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln129_reg_1421_pp0_iter9_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln129_reg_1421_pp0_iter10_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln129_reg_1421_pp0_iter11_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln129_reg_1421_pp0_iter12_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln129_reg_1421_pp0_iter13_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_14_fu_836_p19 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_14_reg_1432 : STD_LOGIC_VECTOR (5 downto 0);
    signal mn_reg_1437 : STD_LOGIC_VECTOR (31 downto 0);
    signal v_reg_1442 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv168_i3_reg_1448 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln132_fu_867_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sc_reg_1458 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_i4_reg_1463 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul174_i3_reg_1468 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_17_fu_895_p19 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul169_i3_reg_1478 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_16_fu_959_p19 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln131_3_fu_674_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln134_fu_813_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal n_4_fu_178 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal add_ln126_fu_648_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_n : STD_LOGIC_VECTOR (8 downto 0);
    signal acc_m_15_fu_182 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_m_15_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal acc_m_14_fu_186 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_m_14_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_m_13_fu_190 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_m_13_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_m_12_fu_194 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_m_12_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_m_11_fu_198 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_m_11_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_m_10_fu_202 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_m_10_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_m_9_fu_206 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_m_9_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_m_fu_210 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_m_load_2 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_w_15_fu_214 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_w_15_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_w_14_fu_218 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_w_14_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_w_13_fu_222 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_w_13_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_w_12_fu_226 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_w_12_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_w_11_fu_230 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_w_11_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_w_10_fu_234 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_w_10_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_w_9_fu_238 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_w_9_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_w_fu_242 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_w_load_2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal block_buf_a_8_ce0_local : STD_LOGIC;
    signal block_buf_a_9_ce0_local : STD_LOGIC;
    signal block_buf_a_10_ce0_local : STD_LOGIC;
    signal block_buf_a_11_ce0_local : STD_LOGIC;
    signal gate_cache_ce0_local : STD_LOGIC;
    signal tmp_s_fu_654_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln131_fu_664_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln131_fu_668_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_13_fu_705_p9 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_13_fu_705_p10 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln131_fu_729_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln131_2_fu_732_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_13_fu_705_p11 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln131_4_fu_740_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal lshr_ln131_fu_744_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_15_fu_754_p17 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_15_fu_754_p18 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_23_fu_797_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln134_2_fu_806_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_14_fu_836_p17 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_895_p17 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_16_fu_959_p17 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal tmp_13_fu_705_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_13_fu_705_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_13_fu_705_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_13_fu_705_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_15_fu_754_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_15_fu_754_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_15_fu_754_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_15_fu_754_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_15_fu_754_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_15_fu_754_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_15_fu_754_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_15_fu_754_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_14_fu_836_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_14_fu_836_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_14_fu_836_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_14_fu_836_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_14_fu_836_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_14_fu_836_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_14_fu_836_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_14_fu_836_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_17_fu_895_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_17_fu_895_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_17_fu_895_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_17_fu_895_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_17_fu_895_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_17_fu_895_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_17_fu_895_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_17_fu_895_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_16_fu_959_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_16_fu_959_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_16_fu_959_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_16_fu_959_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_16_fu_959_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_16_fu_959_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_16_fu_959_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_16_fu_959_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component swiglu_fadd_32ns_32ns_32_4_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component swiglu_fmul_32ns_32ns_32_3_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component swiglu_uitofp_32ns_32_3_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component swiglu_sparsemux_9_2_8_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (1 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (7 downto 0);
        def : IN STD_LOGIC_VECTOR (7 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component swiglu_sparsemux_17_3_6_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (2 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (2 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (2 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (2 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (2 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (2 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (2 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (2 downto 0);
        din7_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (5 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        din2 : IN STD_LOGIC_VECTOR (5 downto 0);
        din3 : IN STD_LOGIC_VECTOR (5 downto 0);
        din4 : IN STD_LOGIC_VECTOR (5 downto 0);
        din5 : IN STD_LOGIC_VECTOR (5 downto 0);
        din6 : IN STD_LOGIC_VECTOR (5 downto 0);
        din7 : IN STD_LOGIC_VECTOR (5 downto 0);
        def : IN STD_LOGIC_VECTOR (5 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (5 downto 0) );
    end component;


    component swiglu_sparsemux_17_3_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (2 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (2 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (2 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (2 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (2 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (2 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (2 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (2 downto 0);
        din7_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (31 downto 0);
        din7 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component swiglu_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_9_2_8_1_1_U327 : component swiglu_sparsemux_9_2_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 8,
        CASE1 => "01",
        din1_WIDTH => 8,
        CASE2 => "10",
        din2_WIDTH => 8,
        CASE3 => "11",
        din3_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => block_buf_a_8_q0,
        din1 => block_buf_a_9_q0,
        din2 => block_buf_a_10_q0,
        din3 => block_buf_a_11_q0,
        def => tmp_13_fu_705_p9,
        sel => tmp_13_fu_705_p10,
        dout => tmp_13_fu_705_p11);

    sparsemux_17_3_6_1_1_U328 : component swiglu_sparsemux_17_3_6_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 6,
        CASE1 => "001",
        din1_WIDTH => 6,
        CASE2 => "010",
        din2_WIDTH => 6,
        CASE3 => "011",
        din3_WIDTH => 6,
        CASE4 => "100",
        din4_WIDTH => 6,
        CASE5 => "101",
        din5_WIDTH => 6,
        CASE6 => "110",
        din6_WIDTH => 6,
        CASE7 => "111",
        din7_WIDTH => 6,
        def_WIDTH => 6,
        sel_WIDTH => 3,
        dout_WIDTH => 6)
    port map (
        din0 => empty_36,
        din1 => empty_37,
        din2 => empty_38,
        din3 => empty,
        din4 => mn6_35,
        din5 => mn6_36,
        din6 => mn6_37,
        din7 => mn6_38,
        def => tmp_15_fu_754_p17,
        sel => tmp_15_fu_754_p18,
        dout => tmp_15_fu_754_p19);

    sparsemux_17_3_6_1_1_U329 : component swiglu_sparsemux_17_3_6_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 6,
        CASE1 => "001",
        din1_WIDTH => 6,
        CASE2 => "010",
        din2_WIDTH => 6,
        CASE3 => "011",
        din3_WIDTH => 6,
        CASE4 => "100",
        din4_WIDTH => 6,
        CASE5 => "101",
        din5_WIDTH => 6,
        CASE6 => "110",
        din6_WIDTH => 6,
        CASE7 => "111",
        din7_WIDTH => 6,
        def_WIDTH => 6,
        sel_WIDTH => 3,
        dout_WIDTH => 6)
    port map (
        din0 => empty_32,
        din1 => empty_33,
        din2 => empty_34,
        din3 => empty_35,
        din4 => sc6_36,
        din5 => sc6_31,
        din6 => sc6_37,
        din7 => sc6_38,
        def => tmp_14_fu_836_p17,
        sel => trunc_ln129_5_reg_1396_pp0_iter3_reg,
        dout => tmp_14_fu_836_p19);

    sparsemux_17_3_32_1_1_U330 : component swiglu_sparsemux_17_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 32,
        CASE1 => "001",
        din1_WIDTH => 32,
        CASE2 => "010",
        din2_WIDTH => 32,
        CASE3 => "011",
        din3_WIDTH => 32,
        CASE4 => "100",
        din4_WIDTH => 32,
        CASE5 => "101",
        din5_WIDTH => 32,
        CASE6 => "110",
        din6_WIDTH => 32,
        CASE7 => "111",
        din7_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => ap_sig_allocacmp_acc_m_load_2,
        din1 => ap_sig_allocacmp_acc_m_9_load_1,
        din2 => ap_sig_allocacmp_acc_m_10_load_1,
        din3 => ap_sig_allocacmp_acc_m_11_load_1,
        din4 => ap_sig_allocacmp_acc_m_12_load_1,
        din5 => ap_sig_allocacmp_acc_m_13_load_1,
        din6 => ap_sig_allocacmp_acc_m_14_load_1,
        din7 => ap_sig_allocacmp_acc_m_15_load_1,
        def => tmp_17_fu_895_p17,
        sel => trunc_ln129_reg_1421_pp0_iter7_reg,
        dout => tmp_17_fu_895_p19);

    sparsemux_17_3_32_1_1_U331 : component swiglu_sparsemux_17_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 32,
        CASE1 => "001",
        din1_WIDTH => 32,
        CASE2 => "010",
        din2_WIDTH => 32,
        CASE3 => "011",
        din3_WIDTH => 32,
        CASE4 => "100",
        din4_WIDTH => 32,
        CASE5 => "101",
        din5_WIDTH => 32,
        CASE6 => "110",
        din6_WIDTH => 32,
        CASE7 => "111",
        din7_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => ap_sig_allocacmp_acc_w_load_2,
        din1 => ap_sig_allocacmp_acc_w_9_load_1,
        din2 => ap_sig_allocacmp_acc_w_10_load_1,
        din3 => ap_sig_allocacmp_acc_w_11_load_1,
        din4 => ap_sig_allocacmp_acc_w_12_load_1,
        din5 => ap_sig_allocacmp_acc_w_13_load_1,
        din6 => ap_sig_allocacmp_acc_w_14_load_1,
        din7 => ap_sig_allocacmp_acc_w_15_load_1,
        def => tmp_16_fu_959_p17,
        sel => trunc_ln129_reg_1421_pp0_iter10_reg,
        dout => tmp_16_fu_959_p19);

    flow_control_loop_pipe_sequential_init_U : component swiglu_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    acc_m_10_fu_202_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_m_10_fu_202 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln129_reg_1421_pp0_iter10_reg = ap_const_lv3_2))) then 
                    acc_m_10_fu_202 <= grp_fu_16169_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    acc_m_11_fu_198_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_m_11_fu_198 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln129_reg_1421_pp0_iter10_reg = ap_const_lv3_3))) then 
                    acc_m_11_fu_198 <= grp_fu_16169_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    acc_m_12_fu_194_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_m_12_fu_194 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln129_reg_1421_pp0_iter10_reg = ap_const_lv3_4))) then 
                    acc_m_12_fu_194 <= grp_fu_16169_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    acc_m_13_fu_190_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_m_13_fu_190 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln129_reg_1421_pp0_iter10_reg = ap_const_lv3_5))) then 
                    acc_m_13_fu_190 <= grp_fu_16169_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    acc_m_14_fu_186_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_m_14_fu_186 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln129_reg_1421_pp0_iter10_reg = ap_const_lv3_6))) then 
                    acc_m_14_fu_186 <= grp_fu_16169_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    acc_m_15_fu_182_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_m_15_fu_182 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln129_reg_1421_pp0_iter10_reg = ap_const_lv3_7))) then 
                    acc_m_15_fu_182 <= grp_fu_16169_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    acc_m_9_fu_206_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_m_9_fu_206 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln129_reg_1421_pp0_iter10_reg = ap_const_lv3_1))) then 
                    acc_m_9_fu_206 <= grp_fu_16169_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    acc_m_fu_210_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_m_fu_210 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln129_reg_1421_pp0_iter10_reg = ap_const_lv3_0))) then 
                    acc_m_fu_210 <= grp_fu_16169_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    acc_w_10_fu_234_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_w_10_fu_234 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln129_reg_1421_pp0_iter13_reg = ap_const_lv3_2))) then 
                    acc_w_10_fu_234 <= grp_fu_16173_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    acc_w_11_fu_230_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_w_11_fu_230 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln129_reg_1421_pp0_iter13_reg = ap_const_lv3_3))) then 
                    acc_w_11_fu_230 <= grp_fu_16173_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    acc_w_12_fu_226_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_w_12_fu_226 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln129_reg_1421_pp0_iter13_reg = ap_const_lv3_4))) then 
                    acc_w_12_fu_226 <= grp_fu_16173_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    acc_w_13_fu_222_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_w_13_fu_222 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln129_reg_1421_pp0_iter13_reg = ap_const_lv3_5))) then 
                    acc_w_13_fu_222 <= grp_fu_16173_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    acc_w_14_fu_218_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_w_14_fu_218 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln129_reg_1421_pp0_iter13_reg = ap_const_lv3_6))) then 
                    acc_w_14_fu_218 <= grp_fu_16173_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    acc_w_15_fu_214_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_w_15_fu_214 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln129_reg_1421_pp0_iter13_reg = ap_const_lv3_7))) then 
                    acc_w_15_fu_214 <= grp_fu_16173_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    acc_w_9_fu_238_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_w_9_fu_238 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln129_reg_1421_pp0_iter13_reg = ap_const_lv3_1))) then 
                    acc_w_9_fu_238 <= grp_fu_16173_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    acc_w_fu_242_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_w_fu_242 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln129_reg_1421_pp0_iter13_reg = ap_const_lv3_0))) then 
                    acc_w_fu_242 <= grp_fu_16173_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    n_4_fu_178_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln126_fu_642_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    n_4_fu_178 <= add_ln126_fu_648_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    n_4_fu_178 <= ap_const_lv9_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                conv168_i3_reg_1448 <= grp_fu_16184_p_dout0;
                icmp_ln126_reg_1372_pp0_iter10_reg <= icmp_ln126_reg_1372_pp0_iter9_reg;
                icmp_ln126_reg_1372_pp0_iter11_reg <= icmp_ln126_reg_1372_pp0_iter10_reg;
                icmp_ln126_reg_1372_pp0_iter12_reg <= icmp_ln126_reg_1372_pp0_iter11_reg;
                icmp_ln126_reg_1372_pp0_iter2_reg <= icmp_ln126_reg_1372_pp0_iter1_reg;
                icmp_ln126_reg_1372_pp0_iter3_reg <= icmp_ln126_reg_1372_pp0_iter2_reg;
                icmp_ln126_reg_1372_pp0_iter4_reg <= icmp_ln126_reg_1372_pp0_iter3_reg;
                icmp_ln126_reg_1372_pp0_iter5_reg <= icmp_ln126_reg_1372_pp0_iter4_reg;
                icmp_ln126_reg_1372_pp0_iter6_reg <= icmp_ln126_reg_1372_pp0_iter5_reg;
                icmp_ln126_reg_1372_pp0_iter7_reg <= icmp_ln126_reg_1372_pp0_iter6_reg;
                icmp_ln126_reg_1372_pp0_iter8_reg <= icmp_ln126_reg_1372_pp0_iter7_reg;
                icmp_ln126_reg_1372_pp0_iter9_reg <= icmp_ln126_reg_1372_pp0_iter8_reg;
                mn_reg_1437 <= grp_fu_16181_p_dout0;
                mul169_i3_reg_1478 <= grp_fu_16177_p_dout0;
                mul174_i3_reg_1468 <= grp_fu_2390_p_dout0;
                mul_i4_reg_1463 <= grp_fu_2386_p_dout0;
                n_reg_1363_pp0_iter2_reg <= n_reg_1363_pp0_iter1_reg;
                sc_reg_1458 <= grp_fu_16187_p_dout0;
                tmp_14_reg_1432 <= tmp_14_fu_836_p19;
                trunc_ln129_5_reg_1396_pp0_iter2_reg <= trunc_ln129_5_reg_1396;
                trunc_ln129_5_reg_1396_pp0_iter3_reg <= trunc_ln129_5_reg_1396_pp0_iter2_reg;
                trunc_ln129_reg_1421 <= trunc_ln129_fu_794_p1;
                trunc_ln129_reg_1421_pp0_iter10_reg <= trunc_ln129_reg_1421_pp0_iter9_reg;
                trunc_ln129_reg_1421_pp0_iter11_reg <= trunc_ln129_reg_1421_pp0_iter10_reg;
                trunc_ln129_reg_1421_pp0_iter12_reg <= trunc_ln129_reg_1421_pp0_iter11_reg;
                trunc_ln129_reg_1421_pp0_iter13_reg <= trunc_ln129_reg_1421_pp0_iter12_reg;
                trunc_ln129_reg_1421_pp0_iter4_reg <= trunc_ln129_reg_1421;
                trunc_ln129_reg_1421_pp0_iter5_reg <= trunc_ln129_reg_1421_pp0_iter4_reg;
                trunc_ln129_reg_1421_pp0_iter6_reg <= trunc_ln129_reg_1421_pp0_iter5_reg;
                trunc_ln129_reg_1421_pp0_iter7_reg <= trunc_ln129_reg_1421_pp0_iter6_reg;
                trunc_ln129_reg_1421_pp0_iter8_reg <= trunc_ln129_reg_1421_pp0_iter7_reg;
                trunc_ln129_reg_1421_pp0_iter9_reg <= trunc_ln129_reg_1421_pp0_iter8_reg;
                v_reg_1442 <= gate_cache_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln126_reg_1372 <= icmp_ln126_fu_642_p2;
                icmp_ln126_reg_1372_pp0_iter1_reg <= icmp_ln126_reg_1372;
                n_reg_1363 <= ap_sig_allocacmp_n;
                n_reg_1363_pp0_iter1_reg <= n_reg_1363;
                nibble_reg_1401 <= nibble_fu_750_p1;
                tmp_15_reg_1406 <= tmp_15_fu_754_p19;
                trunc_ln129_5_reg_1396 <= n_reg_1363(7 downto 5);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    acc_m_32_load_out <= acc_m_fu_210;

    acc_m_32_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln126_reg_1372_pp0_iter12_reg, ap_loop_exit_ready_pp0_iter13_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (icmp_ln126_reg_1372_pp0_iter12_reg = ap_const_lv1_1))) then 
            acc_m_32_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_m_32_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_m_33_load_out <= acc_m_9_fu_206;

    acc_m_33_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln126_reg_1372_pp0_iter12_reg, ap_loop_exit_ready_pp0_iter13_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (icmp_ln126_reg_1372_pp0_iter12_reg = ap_const_lv1_1))) then 
            acc_m_33_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_m_33_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_m_34_load_out <= acc_m_10_fu_202;

    acc_m_34_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln126_reg_1372_pp0_iter12_reg, ap_loop_exit_ready_pp0_iter13_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (icmp_ln126_reg_1372_pp0_iter12_reg = ap_const_lv1_1))) then 
            acc_m_34_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_m_34_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_m_35_load_out <= acc_m_11_fu_198;

    acc_m_35_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln126_reg_1372_pp0_iter12_reg, ap_loop_exit_ready_pp0_iter13_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (icmp_ln126_reg_1372_pp0_iter12_reg = ap_const_lv1_1))) then 
            acc_m_35_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_m_35_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_m_36_load_out <= acc_m_12_fu_194;

    acc_m_36_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln126_reg_1372_pp0_iter12_reg, ap_loop_exit_ready_pp0_iter13_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (icmp_ln126_reg_1372_pp0_iter12_reg = ap_const_lv1_1))) then 
            acc_m_36_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_m_36_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_m_37_load_out <= acc_m_13_fu_190;

    acc_m_37_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln126_reg_1372_pp0_iter12_reg, ap_loop_exit_ready_pp0_iter13_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (icmp_ln126_reg_1372_pp0_iter12_reg = ap_const_lv1_1))) then 
            acc_m_37_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_m_37_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_m_38_load_out <= acc_m_14_fu_186;

    acc_m_38_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln126_reg_1372_pp0_iter12_reg, ap_loop_exit_ready_pp0_iter13_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (icmp_ln126_reg_1372_pp0_iter12_reg = ap_const_lv1_1))) then 
            acc_m_38_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_m_38_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_m_39_load_out <= acc_m_15_fu_182;

    acc_m_39_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln126_reg_1372_pp0_iter12_reg, ap_loop_exit_ready_pp0_iter13_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (icmp_ln126_reg_1372_pp0_iter12_reg = ap_const_lv1_1))) then 
            acc_m_39_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_m_39_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_w_32_load_out <= acc_w_fu_242;

    acc_w_32_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln126_reg_1372_pp0_iter12_reg, ap_loop_exit_ready_pp0_iter13_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (icmp_ln126_reg_1372_pp0_iter12_reg = ap_const_lv1_1))) then 
            acc_w_32_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_w_32_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_w_33_load_out <= acc_w_9_fu_238;

    acc_w_33_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln126_reg_1372_pp0_iter12_reg, ap_loop_exit_ready_pp0_iter13_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (icmp_ln126_reg_1372_pp0_iter12_reg = ap_const_lv1_1))) then 
            acc_w_33_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_w_33_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_w_34_load_out <= acc_w_10_fu_234;

    acc_w_34_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln126_reg_1372_pp0_iter12_reg, ap_loop_exit_ready_pp0_iter13_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (icmp_ln126_reg_1372_pp0_iter12_reg = ap_const_lv1_1))) then 
            acc_w_34_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_w_34_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_w_35_load_out <= acc_w_11_fu_230;

    acc_w_35_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln126_reg_1372_pp0_iter12_reg, ap_loop_exit_ready_pp0_iter13_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (icmp_ln126_reg_1372_pp0_iter12_reg = ap_const_lv1_1))) then 
            acc_w_35_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_w_35_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_w_36_load_out <= acc_w_12_fu_226;

    acc_w_36_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln126_reg_1372_pp0_iter12_reg, ap_loop_exit_ready_pp0_iter13_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (icmp_ln126_reg_1372_pp0_iter12_reg = ap_const_lv1_1))) then 
            acc_w_36_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_w_36_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_w_37_load_out <= acc_w_13_fu_222;

    acc_w_37_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln126_reg_1372_pp0_iter12_reg, ap_loop_exit_ready_pp0_iter13_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (icmp_ln126_reg_1372_pp0_iter12_reg = ap_const_lv1_1))) then 
            acc_w_37_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_w_37_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_w_38_load_out <= acc_w_14_fu_218;

    acc_w_38_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln126_reg_1372_pp0_iter12_reg, ap_loop_exit_ready_pp0_iter13_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (icmp_ln126_reg_1372_pp0_iter12_reg = ap_const_lv1_1))) then 
            acc_w_38_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_w_38_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_w_39_load_out <= acc_w_15_fu_214;

    acc_w_39_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln126_reg_1372_pp0_iter12_reg, ap_loop_exit_ready_pp0_iter13_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (icmp_ln126_reg_1372_pp0_iter12_reg = ap_const_lv1_1))) then 
            acc_w_39_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_w_39_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln126_fu_648_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_n) + unsigned(ap_const_lv9_1));
    add_ln131_fu_668_p2 <= std_logic_vector(unsigned(zext_ln131_fu_664_p1) + unsigned(ap_const_lv6_4));
    add_ln134_2_fu_806_p3 <= (tmp_23_fu_797_p4 & n_reg_1363_pp0_iter2_reg);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln126_fu_642_p2)
    begin
        if (((icmp_ln126_fu_642_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter13_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_acc_m_10_load_1_assign_proc : process(ap_enable_reg_pp0_iter11, trunc_ln129_reg_1421_pp0_iter10_reg, ap_block_pp0_stage0, acc_m_10_fu_202, grp_fu_16169_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln129_reg_1421_pp0_iter10_reg = ap_const_lv3_2))) then 
            ap_sig_allocacmp_acc_m_10_load_1 <= grp_fu_16169_p_dout0;
        else 
            ap_sig_allocacmp_acc_m_10_load_1 <= acc_m_10_fu_202;
        end if; 
    end process;


    ap_sig_allocacmp_acc_m_11_load_1_assign_proc : process(ap_enable_reg_pp0_iter11, trunc_ln129_reg_1421_pp0_iter10_reg, ap_block_pp0_stage0, acc_m_11_fu_198, grp_fu_16169_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln129_reg_1421_pp0_iter10_reg = ap_const_lv3_3))) then 
            ap_sig_allocacmp_acc_m_11_load_1 <= grp_fu_16169_p_dout0;
        else 
            ap_sig_allocacmp_acc_m_11_load_1 <= acc_m_11_fu_198;
        end if; 
    end process;


    ap_sig_allocacmp_acc_m_12_load_1_assign_proc : process(ap_enable_reg_pp0_iter11, trunc_ln129_reg_1421_pp0_iter10_reg, ap_block_pp0_stage0, acc_m_12_fu_194, grp_fu_16169_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln129_reg_1421_pp0_iter10_reg = ap_const_lv3_4))) then 
            ap_sig_allocacmp_acc_m_12_load_1 <= grp_fu_16169_p_dout0;
        else 
            ap_sig_allocacmp_acc_m_12_load_1 <= acc_m_12_fu_194;
        end if; 
    end process;


    ap_sig_allocacmp_acc_m_13_load_1_assign_proc : process(ap_enable_reg_pp0_iter11, trunc_ln129_reg_1421_pp0_iter10_reg, ap_block_pp0_stage0, acc_m_13_fu_190, grp_fu_16169_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln129_reg_1421_pp0_iter10_reg = ap_const_lv3_5))) then 
            ap_sig_allocacmp_acc_m_13_load_1 <= grp_fu_16169_p_dout0;
        else 
            ap_sig_allocacmp_acc_m_13_load_1 <= acc_m_13_fu_190;
        end if; 
    end process;


    ap_sig_allocacmp_acc_m_14_load_1_assign_proc : process(ap_enable_reg_pp0_iter11, trunc_ln129_reg_1421_pp0_iter10_reg, ap_block_pp0_stage0, acc_m_14_fu_186, grp_fu_16169_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln129_reg_1421_pp0_iter10_reg = ap_const_lv3_6))) then 
            ap_sig_allocacmp_acc_m_14_load_1 <= grp_fu_16169_p_dout0;
        else 
            ap_sig_allocacmp_acc_m_14_load_1 <= acc_m_14_fu_186;
        end if; 
    end process;


    ap_sig_allocacmp_acc_m_15_load_1_assign_proc : process(ap_enable_reg_pp0_iter11, trunc_ln129_reg_1421_pp0_iter10_reg, ap_block_pp0_stage0, acc_m_15_fu_182, grp_fu_16169_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln129_reg_1421_pp0_iter10_reg = ap_const_lv3_7))) then 
            ap_sig_allocacmp_acc_m_15_load_1 <= grp_fu_16169_p_dout0;
        else 
            ap_sig_allocacmp_acc_m_15_load_1 <= acc_m_15_fu_182;
        end if; 
    end process;


    ap_sig_allocacmp_acc_m_9_load_1_assign_proc : process(ap_enable_reg_pp0_iter11, trunc_ln129_reg_1421_pp0_iter10_reg, ap_block_pp0_stage0, acc_m_9_fu_206, grp_fu_16169_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln129_reg_1421_pp0_iter10_reg = ap_const_lv3_1))) then 
            ap_sig_allocacmp_acc_m_9_load_1 <= grp_fu_16169_p_dout0;
        else 
            ap_sig_allocacmp_acc_m_9_load_1 <= acc_m_9_fu_206;
        end if; 
    end process;


    ap_sig_allocacmp_acc_m_load_2_assign_proc : process(ap_enable_reg_pp0_iter11, trunc_ln129_reg_1421_pp0_iter10_reg, ap_block_pp0_stage0, acc_m_fu_210, grp_fu_16169_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln129_reg_1421_pp0_iter10_reg = ap_const_lv3_0))) then 
            ap_sig_allocacmp_acc_m_load_2 <= grp_fu_16169_p_dout0;
        else 
            ap_sig_allocacmp_acc_m_load_2 <= acc_m_fu_210;
        end if; 
    end process;


    ap_sig_allocacmp_acc_w_10_load_1_assign_proc : process(ap_enable_reg_pp0_iter14, trunc_ln129_reg_1421_pp0_iter13_reg, ap_block_pp0_stage0, acc_w_10_fu_234, grp_fu_16173_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln129_reg_1421_pp0_iter13_reg = ap_const_lv3_2))) then 
            ap_sig_allocacmp_acc_w_10_load_1 <= grp_fu_16173_p_dout0;
        else 
            ap_sig_allocacmp_acc_w_10_load_1 <= acc_w_10_fu_234;
        end if; 
    end process;


    ap_sig_allocacmp_acc_w_11_load_1_assign_proc : process(ap_enable_reg_pp0_iter14, trunc_ln129_reg_1421_pp0_iter13_reg, ap_block_pp0_stage0, acc_w_11_fu_230, grp_fu_16173_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln129_reg_1421_pp0_iter13_reg = ap_const_lv3_3))) then 
            ap_sig_allocacmp_acc_w_11_load_1 <= grp_fu_16173_p_dout0;
        else 
            ap_sig_allocacmp_acc_w_11_load_1 <= acc_w_11_fu_230;
        end if; 
    end process;


    ap_sig_allocacmp_acc_w_12_load_1_assign_proc : process(ap_enable_reg_pp0_iter14, trunc_ln129_reg_1421_pp0_iter13_reg, ap_block_pp0_stage0, acc_w_12_fu_226, grp_fu_16173_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln129_reg_1421_pp0_iter13_reg = ap_const_lv3_4))) then 
            ap_sig_allocacmp_acc_w_12_load_1 <= grp_fu_16173_p_dout0;
        else 
            ap_sig_allocacmp_acc_w_12_load_1 <= acc_w_12_fu_226;
        end if; 
    end process;


    ap_sig_allocacmp_acc_w_13_load_1_assign_proc : process(ap_enable_reg_pp0_iter14, trunc_ln129_reg_1421_pp0_iter13_reg, ap_block_pp0_stage0, acc_w_13_fu_222, grp_fu_16173_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln129_reg_1421_pp0_iter13_reg = ap_const_lv3_5))) then 
            ap_sig_allocacmp_acc_w_13_load_1 <= grp_fu_16173_p_dout0;
        else 
            ap_sig_allocacmp_acc_w_13_load_1 <= acc_w_13_fu_222;
        end if; 
    end process;


    ap_sig_allocacmp_acc_w_14_load_1_assign_proc : process(ap_enable_reg_pp0_iter14, trunc_ln129_reg_1421_pp0_iter13_reg, ap_block_pp0_stage0, acc_w_14_fu_218, grp_fu_16173_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln129_reg_1421_pp0_iter13_reg = ap_const_lv3_6))) then 
            ap_sig_allocacmp_acc_w_14_load_1 <= grp_fu_16173_p_dout0;
        else 
            ap_sig_allocacmp_acc_w_14_load_1 <= acc_w_14_fu_218;
        end if; 
    end process;


    ap_sig_allocacmp_acc_w_15_load_1_assign_proc : process(ap_enable_reg_pp0_iter14, trunc_ln129_reg_1421_pp0_iter13_reg, ap_block_pp0_stage0, acc_w_15_fu_214, grp_fu_16173_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln129_reg_1421_pp0_iter13_reg = ap_const_lv3_7))) then 
            ap_sig_allocacmp_acc_w_15_load_1 <= grp_fu_16173_p_dout0;
        else 
            ap_sig_allocacmp_acc_w_15_load_1 <= acc_w_15_fu_214;
        end if; 
    end process;


    ap_sig_allocacmp_acc_w_9_load_1_assign_proc : process(ap_enable_reg_pp0_iter14, trunc_ln129_reg_1421_pp0_iter13_reg, ap_block_pp0_stage0, acc_w_9_fu_238, grp_fu_16173_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln129_reg_1421_pp0_iter13_reg = ap_const_lv3_1))) then 
            ap_sig_allocacmp_acc_w_9_load_1 <= grp_fu_16173_p_dout0;
        else 
            ap_sig_allocacmp_acc_w_9_load_1 <= acc_w_9_fu_238;
        end if; 
    end process;


    ap_sig_allocacmp_acc_w_load_2_assign_proc : process(ap_enable_reg_pp0_iter14, trunc_ln129_reg_1421_pp0_iter13_reg, ap_block_pp0_stage0, acc_w_fu_242, grp_fu_16173_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln129_reg_1421_pp0_iter13_reg = ap_const_lv3_0))) then 
            ap_sig_allocacmp_acc_w_load_2 <= grp_fu_16173_p_dout0;
        else 
            ap_sig_allocacmp_acc_w_load_2 <= acc_w_fu_242;
        end if; 
    end process;


    ap_sig_allocacmp_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, n_4_fu_178, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_n <= ap_const_lv9_0;
        else 
            ap_sig_allocacmp_n <= n_4_fu_178;
        end if; 
    end process;

    block_buf_a_10_address0 <= zext_ln131_3_fu_674_p1(6 - 1 downto 0);
    block_buf_a_10_ce0 <= block_buf_a_10_ce0_local;

    block_buf_a_10_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            block_buf_a_10_ce0_local <= ap_const_logic_1;
        else 
            block_buf_a_10_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    block_buf_a_11_address0 <= zext_ln131_3_fu_674_p1(6 - 1 downto 0);
    block_buf_a_11_ce0 <= block_buf_a_11_ce0_local;

    block_buf_a_11_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            block_buf_a_11_ce0_local <= ap_const_logic_1;
        else 
            block_buf_a_11_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    block_buf_a_8_address0 <= zext_ln131_3_fu_674_p1(6 - 1 downto 0);
    block_buf_a_8_ce0 <= block_buf_a_8_ce0_local;

    block_buf_a_8_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            block_buf_a_8_ce0_local <= ap_const_logic_1;
        else 
            block_buf_a_8_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    block_buf_a_9_address0 <= zext_ln131_3_fu_674_p1(6 - 1 downto 0);
    block_buf_a_9_ce0 <= block_buf_a_9_ce0_local;

    block_buf_a_9_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            block_buf_a_9_ce0_local <= ap_const_logic_1;
        else 
            block_buf_a_9_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    gate_cache_address0 <= zext_ln134_fu_813_p1(13 - 1 downto 0);
    gate_cache_ce0 <= gate_cache_ce0_local;

    gate_cache_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            gate_cache_ce0_local <= ap_const_logic_1;
        else 
            gate_cache_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_16169_p_ce <= ap_const_logic_1;
    grp_fu_16169_p_din0 <= tmp_17_fu_895_p19;
    grp_fu_16169_p_din1 <= mul174_i3_reg_1468;
    grp_fu_16169_p_opcode <= ap_const_lv2_0;
    grp_fu_16173_p_ce <= ap_const_logic_1;
    grp_fu_16173_p_din0 <= tmp_16_fu_959_p19;
    grp_fu_16173_p_din1 <= mul169_i3_reg_1478;
    grp_fu_16173_p_opcode <= ap_const_lv2_0;
    grp_fu_16177_p_ce <= ap_const_logic_1;
    grp_fu_16177_p_din0 <= mul_i4_reg_1463;
    grp_fu_16177_p_din1 <= sc_reg_1458;
    grp_fu_16181_p_ce <= ap_const_logic_1;
    grp_fu_16181_p_din0 <= zext_ln133_fu_786_p1;
    grp_fu_16184_p_ce <= ap_const_logic_1;
    grp_fu_16184_p_din0 <= zext_ln135_fu_790_p1;
    grp_fu_16187_p_ce <= ap_const_logic_1;
    grp_fu_16187_p_din0 <= zext_ln132_fu_867_p1;
    grp_fu_2386_p_ce <= ap_const_logic_1;
    grp_fu_2386_p_din0 <= v_reg_1442;
    grp_fu_2386_p_din1 <= conv168_i3_reg_1448;
    grp_fu_2390_p_ce <= ap_const_logic_1;
    grp_fu_2390_p_din0 <= v_reg_1442;
    grp_fu_2390_p_din1 <= mn_reg_1437;
    icmp_ln126_fu_642_p2 <= "1" when (ap_sig_allocacmp_n = ap_const_lv9_100) else "0";
    lshr_ln131_fu_744_p2 <= std_logic_vector(shift_right(unsigned(tmp_13_fu_705_p11),to_integer(unsigned('0' & zext_ln131_4_fu_740_p1(8-1 downto 0)))));
    nibble_fu_750_p1 <= lshr_ln131_fu_744_p2(4 - 1 downto 0);
    shl_ln131_2_fu_732_p3 <= (trunc_ln131_fu_729_p1 & ap_const_lv2_0);
    tmp_13_fu_705_p10 <= n_reg_1363(2 downto 1);
    tmp_13_fu_705_p9 <= "XXXXXXXX";
    tmp_14_fu_836_p17 <= "XXXXXX";
    tmp_15_fu_754_p17 <= "XXXXXX";
    tmp_15_fu_754_p18 <= n_reg_1363(7 downto 5);
    tmp_16_fu_959_p17 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_17_fu_895_p17 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_23_fu_797_p4 <= b_2(4 downto 1);
    tmp_s_fu_654_p4 <= ap_sig_allocacmp_n(7 downto 3);
    trunc_ln129_fu_794_p1 <= n_reg_1363_pp0_iter2_reg(3 - 1 downto 0);
    trunc_ln131_fu_729_p1 <= n_reg_1363(1 - 1 downto 0);
    zext_ln131_3_fu_674_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln131_fu_668_p2),64));
    zext_ln131_4_fu_740_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln131_2_fu_732_p3),8));
    zext_ln131_fu_664_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_654_p4),6));
    zext_ln132_fu_867_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_14_reg_1432),32));
    zext_ln133_fu_786_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_15_reg_1406),32));
    zext_ln134_fu_813_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln134_2_fu_806_p3),64));
    zext_ln135_fu_790_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(nibble_reg_1401),32));
end behav;
