-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity swiglu_swiglu_Pipeline_DECODE_MAC_Q6K is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    block_buf_a_16_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    block_buf_a_16_ce0 : OUT STD_LOGIC;
    block_buf_a_16_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    block_buf_a_16_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    block_buf_a_16_ce1 : OUT STD_LOGIC;
    block_buf_a_16_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    block_buf_a_16_address2 : OUT STD_LOGIC_VECTOR (5 downto 0);
    block_buf_a_16_ce2 : OUT STD_LOGIC;
    block_buf_a_16_q2 : IN STD_LOGIC_VECTOR (7 downto 0);
    block_buf_a_17_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    block_buf_a_17_ce0 : OUT STD_LOGIC;
    block_buf_a_17_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    block_buf_a_17_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    block_buf_a_17_ce1 : OUT STD_LOGIC;
    block_buf_a_17_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    block_buf_a_17_address2 : OUT STD_LOGIC_VECTOR (5 downto 0);
    block_buf_a_17_ce2 : OUT STD_LOGIC;
    block_buf_a_17_q2 : IN STD_LOGIC_VECTOR (7 downto 0);
    block_buf_a_18_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    block_buf_a_18_ce0 : OUT STD_LOGIC;
    block_buf_a_18_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    block_buf_a_18_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    block_buf_a_18_ce1 : OUT STD_LOGIC;
    block_buf_a_18_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    block_buf_a_18_address2 : OUT STD_LOGIC_VECTOR (5 downto 0);
    block_buf_a_18_ce2 : OUT STD_LOGIC;
    block_buf_a_18_q2 : IN STD_LOGIC_VECTOR (7 downto 0);
    block_buf_a_19_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    block_buf_a_19_ce0 : OUT STD_LOGIC;
    block_buf_a_19_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    block_buf_a_19_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    block_buf_a_19_ce1 : OUT STD_LOGIC;
    block_buf_a_19_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    block_buf_a_19_address2 : OUT STD_LOGIC_VECTOR (5 downto 0);
    block_buf_a_19_ce2 : OUT STD_LOGIC;
    block_buf_a_19_q2 : IN STD_LOGIC_VECTOR (7 downto 0);
    d : IN STD_LOGIC_VECTOR (31 downto 0);
    b_3 : IN STD_LOGIC_VECTOR (4 downto 0);
    gate_cache_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    gate_cache_ce0 : OUT STD_LOGIC;
    gate_cache_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_load_out_ap_vld : OUT STD_LOGIC;
    acc_1_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_1_load_out_ap_vld : OUT STD_LOGIC;
    acc_2_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_2_load_out_ap_vld : OUT STD_LOGIC;
    acc_3_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_3_load_out_ap_vld : OUT STD_LOGIC;
    acc_4_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_4_load_out_ap_vld : OUT STD_LOGIC;
    acc_5_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_5_load_out_ap_vld : OUT STD_LOGIC;
    acc_6_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_6_load_out_ap_vld : OUT STD_LOGIC;
    acc_7_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_7_load_out_ap_vld : OUT STD_LOGIC;
    grp_fu_16169_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16169_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16169_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_16169_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16169_p_ce : OUT STD_LOGIC;
    grp_fu_2386_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2386_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2386_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2386_p_ce : OUT STD_LOGIC;
    grp_fu_2390_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2390_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2390_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2390_p_ce : OUT STD_LOGIC;
    grp_fu_16177_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16177_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16177_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16177_p_ce : OUT STD_LOGIC;
    grp_fu_16190_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16190_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16190_p_ce : OUT STD_LOGIC;
    grp_fu_16193_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16193_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16193_p_ce : OUT STD_LOGIC );
end;


architecture behav of swiglu_swiglu_Pipeline_DECODE_MAC_Q6K is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv9_100 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter17 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln174_fu_477_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal n_reg_1014 : STD_LOGIC_VECTOR (8 downto 0);
    signal n_reg_1014_pp0_iter1_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal n_reg_1014_pp0_iter2_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal n_reg_1014_pp0_iter3_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal n_reg_1014_pp0_iter4_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal n_reg_1014_pp0_iter5_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal n_reg_1014_pp0_iter6_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal n_reg_1014_pp0_iter7_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal n_reg_1014_pp0_iter8_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln174_reg_1025 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_1025_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_1025_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_1025_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_1025_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_1025_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_1025_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_1025_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_1025_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_1025_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_1025_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_1025_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_1025_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_1025_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_1025_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_1025_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ql_val_fu_644_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ql_val_reg_1089 : STD_LOGIC_VECTOR (3 downto 0);
    signal xor_ln182_fu_705_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln182_reg_1094 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln182_fu_711_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln182_reg_1099 : STD_LOGIC_VECTOR (0 downto 0);
    signal scale_fu_715_p11 : STD_LOGIC_VECTOR (7 downto 0);
    signal scale_reg_1104 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln184_fu_746_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln184_2_fu_751_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv36_i1_reg_1119 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv37_i1_reg_1124 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_i2_reg_1129 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln176_2_fu_755_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln176_2_reg_1134 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln176_2_reg_1134_pp0_iter10_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln176_2_reg_1134_pp0_iter11_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln176_2_reg_1134_pp0_iter12_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln176_2_reg_1134_pp0_iter13_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln176_2_reg_1134_pp0_iter14_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln176_2_reg_1134_pp0_iter15_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln176_2_reg_1134_pp0_iter16_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal weight_reg_1144 : STD_LOGIC_VECTOR (31 downto 0);
    signal gate_cache_load_reg_1149 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul42_i1_reg_1154 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_fu_821_p19 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln176_fu_499_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln181_3_fu_529_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln183_2_fu_563_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln185_fu_774_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal n_1_fu_142 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal n_3_fu_483_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_n : STD_LOGIC_VECTOR (8 downto 0);
    signal acc_7_fu_146 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_7_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter14_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter15_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter16_reg : STD_LOGIC;
    signal acc_6_fu_150 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_6_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_5_fu_154 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_5_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_4_fu_158 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_4_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_3_fu_162 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_3_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_2_fu_166 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_2_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_1_fu_170 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_1_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_fu_174 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal block_buf_a_16_ce2_local : STD_LOGIC;
    signal block_buf_a_16_ce1_local : STD_LOGIC;
    signal block_buf_a_16_ce0_local : STD_LOGIC;
    signal block_buf_a_17_ce2_local : STD_LOGIC;
    signal block_buf_a_17_ce1_local : STD_LOGIC;
    signal block_buf_a_17_ce0_local : STD_LOGIC;
    signal block_buf_a_18_ce2_local : STD_LOGIC;
    signal block_buf_a_18_ce1_local : STD_LOGIC;
    signal block_buf_a_18_ce0_local : STD_LOGIC;
    signal block_buf_a_19_ce2_local : STD_LOGIC;
    signal block_buf_a_19_ce1_local : STD_LOGIC;
    signal block_buf_a_19_ce0_local : STD_LOGIC;
    signal gate_cache_ce0_local : STD_LOGIC;
    signal lshr_ln176_1_fu_489_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_10_fu_507_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln181_fu_517_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln181_cast_fu_521_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_11_fu_537_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln183_fu_547_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal or_ln5_fu_551_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln183_fu_559_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_8_fu_606_p9 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_8_fu_606_p10 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_8_fu_606_p11 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln176_fu_576_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_630_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln179_fu_640_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln180_fu_652_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_9_fu_663_p9 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_9_fu_663_p10 : STD_LOGIC_VECTOR (1 downto 0);
    signal qh_shift_fu_655_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_9_fu_663_p11 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln181_1_fu_687_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal lshr_ln181_fu_691_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal bit_sel_fu_697_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal scale_fu_715_p9 : STD_LOGIC_VECTOR (7 downto 0);
    signal scale_fu_715_p10 : STD_LOGIC_VECTOR (1 downto 0);
    signal q_fu_739_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_12_fu_758_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln1_fu_767_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_s_fu_821_p17 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal tmp_8_fu_606_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_8_fu_606_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_8_fu_606_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_8_fu_606_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_9_fu_663_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_9_fu_663_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_9_fu_663_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_9_fu_663_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal scale_fu_715_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal scale_fu_715_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal scale_fu_715_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal scale_fu_715_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_821_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_821_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_821_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_821_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_821_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_821_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_821_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_821_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component swiglu_fadd_32ns_32ns_32_4_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component swiglu_fmul_32ns_32ns_32_3_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component swiglu_sitofp_32s_32_3_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component swiglu_sparsemux_9_2_8_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (1 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (7 downto 0);
        def : IN STD_LOGIC_VECTOR (7 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component swiglu_sparsemux_17_3_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (2 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (2 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (2 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (2 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (2 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (2 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (2 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (2 downto 0);
        din7_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (31 downto 0);
        din7 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component swiglu_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_9_2_8_1_1_U263 : component swiglu_sparsemux_9_2_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 8,
        CASE1 => "01",
        din1_WIDTH => 8,
        CASE2 => "10",
        din2_WIDTH => 8,
        CASE3 => "11",
        din3_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => block_buf_a_16_q2,
        din1 => block_buf_a_17_q2,
        din2 => block_buf_a_18_q2,
        din3 => block_buf_a_19_q2,
        def => tmp_8_fu_606_p9,
        sel => tmp_8_fu_606_p10,
        dout => tmp_8_fu_606_p11);

    sparsemux_9_2_8_1_1_U264 : component swiglu_sparsemux_9_2_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 8,
        CASE1 => "01",
        din1_WIDTH => 8,
        CASE2 => "10",
        din2_WIDTH => 8,
        CASE3 => "11",
        din3_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => block_buf_a_16_q1,
        din1 => block_buf_a_17_q1,
        din2 => block_buf_a_18_q1,
        din3 => block_buf_a_19_q1,
        def => tmp_9_fu_663_p9,
        sel => tmp_9_fu_663_p10,
        dout => tmp_9_fu_663_p11);

    sparsemux_9_2_8_1_1_U265 : component swiglu_sparsemux_9_2_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 8,
        CASE1 => "01",
        din1_WIDTH => 8,
        CASE2 => "10",
        din2_WIDTH => 8,
        CASE3 => "11",
        din3_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => block_buf_a_16_q0,
        din1 => block_buf_a_17_q0,
        din2 => block_buf_a_18_q0,
        din3 => block_buf_a_19_q0,
        def => scale_fu_715_p9,
        sel => scale_fu_715_p10,
        dout => scale_fu_715_p11);

    sparsemux_17_3_32_1_1_U266 : component swiglu_sparsemux_17_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 32,
        CASE1 => "001",
        din1_WIDTH => 32,
        CASE2 => "010",
        din2_WIDTH => 32,
        CASE3 => "011",
        din3_WIDTH => 32,
        CASE4 => "100",
        din4_WIDTH => 32,
        CASE5 => "101",
        din5_WIDTH => 32,
        CASE6 => "110",
        din6_WIDTH => 32,
        CASE7 => "111",
        din7_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => ap_sig_allocacmp_acc_load_1,
        din1 => ap_sig_allocacmp_acc_1_load_1,
        din2 => ap_sig_allocacmp_acc_2_load_1,
        din3 => ap_sig_allocacmp_acc_3_load_1,
        din4 => ap_sig_allocacmp_acc_4_load_1,
        din5 => ap_sig_allocacmp_acc_5_load_1,
        din6 => ap_sig_allocacmp_acc_6_load_1,
        din7 => ap_sig_allocacmp_acc_7_load_1,
        def => tmp_s_fu_821_p17,
        sel => trunc_ln176_2_reg_1134_pp0_iter13_reg,
        dout => tmp_s_fu_821_p19);

    flow_control_loop_pipe_sequential_init_U : component swiglu_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter16_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter17_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter17 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    acc_1_fu_170_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_1_fu_170 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter17 = ap_const_logic_1) and (trunc_ln176_2_reg_1134_pp0_iter16_reg = ap_const_lv3_1))) then 
                    acc_1_fu_170 <= grp_fu_16169_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    acc_2_fu_166_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_2_fu_166 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter17 = ap_const_logic_1) and (trunc_ln176_2_reg_1134_pp0_iter16_reg = ap_const_lv3_2))) then 
                    acc_2_fu_166 <= grp_fu_16169_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    acc_3_fu_162_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_3_fu_162 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter17 = ap_const_logic_1) and (trunc_ln176_2_reg_1134_pp0_iter16_reg = ap_const_lv3_3))) then 
                    acc_3_fu_162 <= grp_fu_16169_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    acc_4_fu_158_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_4_fu_158 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter17 = ap_const_logic_1) and (trunc_ln176_2_reg_1134_pp0_iter16_reg = ap_const_lv3_4))) then 
                    acc_4_fu_158 <= grp_fu_16169_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    acc_5_fu_154_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_5_fu_154 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter17 = ap_const_logic_1) and (trunc_ln176_2_reg_1134_pp0_iter16_reg = ap_const_lv3_5))) then 
                    acc_5_fu_154 <= grp_fu_16169_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    acc_6_fu_150_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_6_fu_150 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter17 = ap_const_logic_1) and (trunc_ln176_2_reg_1134_pp0_iter16_reg = ap_const_lv3_6))) then 
                    acc_6_fu_150 <= grp_fu_16169_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    acc_7_fu_146_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_7_fu_146 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter17 = ap_const_logic_1) and (trunc_ln176_2_reg_1134_pp0_iter16_reg = ap_const_lv3_7))) then 
                    acc_7_fu_146 <= grp_fu_16169_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    acc_fu_174_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_fu_174 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter17 = ap_const_logic_1) and (trunc_ln176_2_reg_1134_pp0_iter16_reg = ap_const_lv3_0))) then 
                    acc_fu_174 <= grp_fu_16169_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    n_1_fu_142_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln174_fu_477_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    n_1_fu_142 <= n_3_fu_483_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    n_1_fu_142 <= ap_const_lv9_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
                ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
                ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
                ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                conv36_i1_reg_1119 <= grp_fu_16190_p_dout0;
                conv37_i1_reg_1124 <= grp_fu_16193_p_dout0;
                gate_cache_load_reg_1149 <= gate_cache_q0;
                icmp_ln174_reg_1025_pp0_iter10_reg <= icmp_ln174_reg_1025_pp0_iter9_reg;
                icmp_ln174_reg_1025_pp0_iter11_reg <= icmp_ln174_reg_1025_pp0_iter10_reg;
                icmp_ln174_reg_1025_pp0_iter12_reg <= icmp_ln174_reg_1025_pp0_iter11_reg;
                icmp_ln174_reg_1025_pp0_iter13_reg <= icmp_ln174_reg_1025_pp0_iter12_reg;
                icmp_ln174_reg_1025_pp0_iter14_reg <= icmp_ln174_reg_1025_pp0_iter13_reg;
                icmp_ln174_reg_1025_pp0_iter15_reg <= icmp_ln174_reg_1025_pp0_iter14_reg;
                icmp_ln174_reg_1025_pp0_iter2_reg <= icmp_ln174_reg_1025_pp0_iter1_reg;
                icmp_ln174_reg_1025_pp0_iter3_reg <= icmp_ln174_reg_1025_pp0_iter2_reg;
                icmp_ln174_reg_1025_pp0_iter4_reg <= icmp_ln174_reg_1025_pp0_iter3_reg;
                icmp_ln174_reg_1025_pp0_iter5_reg <= icmp_ln174_reg_1025_pp0_iter4_reg;
                icmp_ln174_reg_1025_pp0_iter6_reg <= icmp_ln174_reg_1025_pp0_iter5_reg;
                icmp_ln174_reg_1025_pp0_iter7_reg <= icmp_ln174_reg_1025_pp0_iter6_reg;
                icmp_ln174_reg_1025_pp0_iter8_reg <= icmp_ln174_reg_1025_pp0_iter7_reg;
                icmp_ln174_reg_1025_pp0_iter9_reg <= icmp_ln174_reg_1025_pp0_iter8_reg;
                mul42_i1_reg_1154 <= grp_fu_16177_p_dout0;
                mul_i2_reg_1129 <= grp_fu_2386_p_dout0;
                n_reg_1014_pp0_iter2_reg <= n_reg_1014_pp0_iter1_reg;
                n_reg_1014_pp0_iter3_reg <= n_reg_1014_pp0_iter2_reg;
                n_reg_1014_pp0_iter4_reg <= n_reg_1014_pp0_iter3_reg;
                n_reg_1014_pp0_iter5_reg <= n_reg_1014_pp0_iter4_reg;
                n_reg_1014_pp0_iter6_reg <= n_reg_1014_pp0_iter5_reg;
                n_reg_1014_pp0_iter7_reg <= n_reg_1014_pp0_iter6_reg;
                n_reg_1014_pp0_iter8_reg <= n_reg_1014_pp0_iter7_reg;
                trunc_ln176_2_reg_1134 <= trunc_ln176_2_fu_755_p1;
                trunc_ln176_2_reg_1134_pp0_iter10_reg <= trunc_ln176_2_reg_1134;
                trunc_ln176_2_reg_1134_pp0_iter11_reg <= trunc_ln176_2_reg_1134_pp0_iter10_reg;
                trunc_ln176_2_reg_1134_pp0_iter12_reg <= trunc_ln176_2_reg_1134_pp0_iter11_reg;
                trunc_ln176_2_reg_1134_pp0_iter13_reg <= trunc_ln176_2_reg_1134_pp0_iter12_reg;
                trunc_ln176_2_reg_1134_pp0_iter14_reg <= trunc_ln176_2_reg_1134_pp0_iter13_reg;
                trunc_ln176_2_reg_1134_pp0_iter15_reg <= trunc_ln176_2_reg_1134_pp0_iter14_reg;
                trunc_ln176_2_reg_1134_pp0_iter16_reg <= trunc_ln176_2_reg_1134_pp0_iter15_reg;
                weight_reg_1144 <= grp_fu_2390_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln174_reg_1025 <= icmp_ln174_fu_477_p2;
                icmp_ln174_reg_1025_pp0_iter1_reg <= icmp_ln174_reg_1025;
                n_reg_1014 <= ap_sig_allocacmp_n;
                n_reg_1014_pp0_iter1_reg <= n_reg_1014;
                ql_val_reg_1089 <= ql_val_fu_644_p3;
                scale_reg_1104 <= scale_fu_715_p11;
                trunc_ln182_reg_1099 <= trunc_ln182_fu_711_p1;
                xor_ln182_reg_1094 <= xor_ln182_fu_705_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    acc_1_load_out <= acc_1_fu_170;

    acc_1_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln174_reg_1025_pp0_iter15_reg, ap_loop_exit_ready_pp0_iter16_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter16_reg = ap_const_logic_1) and (icmp_ln174_reg_1025_pp0_iter15_reg = ap_const_lv1_1))) then 
            acc_1_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_1_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_2_load_out <= acc_2_fu_166;

    acc_2_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln174_reg_1025_pp0_iter15_reg, ap_loop_exit_ready_pp0_iter16_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter16_reg = ap_const_logic_1) and (icmp_ln174_reg_1025_pp0_iter15_reg = ap_const_lv1_1))) then 
            acc_2_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_2_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_3_load_out <= acc_3_fu_162;

    acc_3_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln174_reg_1025_pp0_iter15_reg, ap_loop_exit_ready_pp0_iter16_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter16_reg = ap_const_logic_1) and (icmp_ln174_reg_1025_pp0_iter15_reg = ap_const_lv1_1))) then 
            acc_3_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_3_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_4_load_out <= acc_4_fu_158;

    acc_4_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln174_reg_1025_pp0_iter15_reg, ap_loop_exit_ready_pp0_iter16_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter16_reg = ap_const_logic_1) and (icmp_ln174_reg_1025_pp0_iter15_reg = ap_const_lv1_1))) then 
            acc_4_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_4_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_5_load_out <= acc_5_fu_154;

    acc_5_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln174_reg_1025_pp0_iter15_reg, ap_loop_exit_ready_pp0_iter16_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter16_reg = ap_const_logic_1) and (icmp_ln174_reg_1025_pp0_iter15_reg = ap_const_lv1_1))) then 
            acc_5_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_5_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_6_load_out <= acc_6_fu_150;

    acc_6_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln174_reg_1025_pp0_iter15_reg, ap_loop_exit_ready_pp0_iter16_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter16_reg = ap_const_logic_1) and (icmp_ln174_reg_1025_pp0_iter15_reg = ap_const_lv1_1))) then 
            acc_6_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_6_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_7_load_out <= acc_7_fu_146;

    acc_7_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln174_reg_1025_pp0_iter15_reg, ap_loop_exit_ready_pp0_iter16_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter16_reg = ap_const_logic_1) and (icmp_ln174_reg_1025_pp0_iter15_reg = ap_const_lv1_1))) then 
            acc_7_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_7_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_load_out <= acc_fu_174;

    acc_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln174_reg_1025_pp0_iter15_reg, ap_loop_exit_ready_pp0_iter16_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter16_reg = ap_const_logic_1) and (icmp_ln174_reg_1025_pp0_iter15_reg = ap_const_lv1_1))) then 
            acc_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln1_fu_767_p3 <= (tmp_12_fu_758_p4 & n_reg_1014_pp0_iter8_reg);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln174_fu_477_p2)
    begin
        if (((icmp_ln174_fu_477_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter16_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter16_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17)
    begin
        if (((ap_enable_reg_pp0_iter17 = ap_const_logic_0) and (ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_acc_1_load_1_assign_proc : process(ap_enable_reg_pp0_iter17, trunc_ln176_2_reg_1134_pp0_iter16_reg, ap_block_pp0_stage0, acc_1_fu_170, grp_fu_16169_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter17 = ap_const_logic_1) and (trunc_ln176_2_reg_1134_pp0_iter16_reg = ap_const_lv3_1))) then 
            ap_sig_allocacmp_acc_1_load_1 <= grp_fu_16169_p_dout0;
        else 
            ap_sig_allocacmp_acc_1_load_1 <= acc_1_fu_170;
        end if; 
    end process;


    ap_sig_allocacmp_acc_2_load_1_assign_proc : process(ap_enable_reg_pp0_iter17, trunc_ln176_2_reg_1134_pp0_iter16_reg, ap_block_pp0_stage0, acc_2_fu_166, grp_fu_16169_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter17 = ap_const_logic_1) and (trunc_ln176_2_reg_1134_pp0_iter16_reg = ap_const_lv3_2))) then 
            ap_sig_allocacmp_acc_2_load_1 <= grp_fu_16169_p_dout0;
        else 
            ap_sig_allocacmp_acc_2_load_1 <= acc_2_fu_166;
        end if; 
    end process;


    ap_sig_allocacmp_acc_3_load_1_assign_proc : process(ap_enable_reg_pp0_iter17, trunc_ln176_2_reg_1134_pp0_iter16_reg, ap_block_pp0_stage0, acc_3_fu_162, grp_fu_16169_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter17 = ap_const_logic_1) and (trunc_ln176_2_reg_1134_pp0_iter16_reg = ap_const_lv3_3))) then 
            ap_sig_allocacmp_acc_3_load_1 <= grp_fu_16169_p_dout0;
        else 
            ap_sig_allocacmp_acc_3_load_1 <= acc_3_fu_162;
        end if; 
    end process;


    ap_sig_allocacmp_acc_4_load_1_assign_proc : process(ap_enable_reg_pp0_iter17, trunc_ln176_2_reg_1134_pp0_iter16_reg, ap_block_pp0_stage0, acc_4_fu_158, grp_fu_16169_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter17 = ap_const_logic_1) and (trunc_ln176_2_reg_1134_pp0_iter16_reg = ap_const_lv3_4))) then 
            ap_sig_allocacmp_acc_4_load_1 <= grp_fu_16169_p_dout0;
        else 
            ap_sig_allocacmp_acc_4_load_1 <= acc_4_fu_158;
        end if; 
    end process;


    ap_sig_allocacmp_acc_5_load_1_assign_proc : process(ap_enable_reg_pp0_iter17, trunc_ln176_2_reg_1134_pp0_iter16_reg, ap_block_pp0_stage0, acc_5_fu_154, grp_fu_16169_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter17 = ap_const_logic_1) and (trunc_ln176_2_reg_1134_pp0_iter16_reg = ap_const_lv3_5))) then 
            ap_sig_allocacmp_acc_5_load_1 <= grp_fu_16169_p_dout0;
        else 
            ap_sig_allocacmp_acc_5_load_1 <= acc_5_fu_154;
        end if; 
    end process;


    ap_sig_allocacmp_acc_6_load_1_assign_proc : process(ap_enable_reg_pp0_iter17, trunc_ln176_2_reg_1134_pp0_iter16_reg, ap_block_pp0_stage0, acc_6_fu_150, grp_fu_16169_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter17 = ap_const_logic_1) and (trunc_ln176_2_reg_1134_pp0_iter16_reg = ap_const_lv3_6))) then 
            ap_sig_allocacmp_acc_6_load_1 <= grp_fu_16169_p_dout0;
        else 
            ap_sig_allocacmp_acc_6_load_1 <= acc_6_fu_150;
        end if; 
    end process;


    ap_sig_allocacmp_acc_7_load_1_assign_proc : process(ap_enable_reg_pp0_iter17, trunc_ln176_2_reg_1134_pp0_iter16_reg, ap_block_pp0_stage0, acc_7_fu_146, grp_fu_16169_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter17 = ap_const_logic_1) and (trunc_ln176_2_reg_1134_pp0_iter16_reg = ap_const_lv3_7))) then 
            ap_sig_allocacmp_acc_7_load_1 <= grp_fu_16169_p_dout0;
        else 
            ap_sig_allocacmp_acc_7_load_1 <= acc_7_fu_146;
        end if; 
    end process;


    ap_sig_allocacmp_acc_load_1_assign_proc : process(ap_enable_reg_pp0_iter17, trunc_ln176_2_reg_1134_pp0_iter16_reg, ap_block_pp0_stage0, acc_fu_174, grp_fu_16169_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter17 = ap_const_logic_1) and (trunc_ln176_2_reg_1134_pp0_iter16_reg = ap_const_lv3_0))) then 
            ap_sig_allocacmp_acc_load_1 <= grp_fu_16169_p_dout0;
        else 
            ap_sig_allocacmp_acc_load_1 <= acc_fu_174;
        end if; 
    end process;


    ap_sig_allocacmp_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, n_1_fu_142, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_n <= ap_const_lv9_0;
        else 
            ap_sig_allocacmp_n <= n_1_fu_142;
        end if; 
    end process;

    bit_sel_fu_697_p3 <= lshr_ln181_fu_691_p2(1 downto 1);
    block_buf_a_16_address0 <= zext_ln183_2_fu_563_p1(6 - 1 downto 0);
    block_buf_a_16_address1 <= zext_ln181_3_fu_529_p1(6 - 1 downto 0);
    block_buf_a_16_address2 <= zext_ln176_fu_499_p1(6 - 1 downto 0);
    block_buf_a_16_ce0 <= block_buf_a_16_ce0_local;

    block_buf_a_16_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            block_buf_a_16_ce0_local <= ap_const_logic_1;
        else 
            block_buf_a_16_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    block_buf_a_16_ce1 <= block_buf_a_16_ce1_local;

    block_buf_a_16_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            block_buf_a_16_ce1_local <= ap_const_logic_1;
        else 
            block_buf_a_16_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    block_buf_a_16_ce2 <= block_buf_a_16_ce2_local;

    block_buf_a_16_ce2_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            block_buf_a_16_ce2_local <= ap_const_logic_1;
        else 
            block_buf_a_16_ce2_local <= ap_const_logic_0;
        end if; 
    end process;

    block_buf_a_17_address0 <= zext_ln183_2_fu_563_p1(6 - 1 downto 0);
    block_buf_a_17_address1 <= zext_ln181_3_fu_529_p1(6 - 1 downto 0);
    block_buf_a_17_address2 <= zext_ln176_fu_499_p1(6 - 1 downto 0);
    block_buf_a_17_ce0 <= block_buf_a_17_ce0_local;

    block_buf_a_17_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            block_buf_a_17_ce0_local <= ap_const_logic_1;
        else 
            block_buf_a_17_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    block_buf_a_17_ce1 <= block_buf_a_17_ce1_local;

    block_buf_a_17_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            block_buf_a_17_ce1_local <= ap_const_logic_1;
        else 
            block_buf_a_17_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    block_buf_a_17_ce2 <= block_buf_a_17_ce2_local;

    block_buf_a_17_ce2_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            block_buf_a_17_ce2_local <= ap_const_logic_1;
        else 
            block_buf_a_17_ce2_local <= ap_const_logic_0;
        end if; 
    end process;

    block_buf_a_18_address0 <= zext_ln183_2_fu_563_p1(6 - 1 downto 0);
    block_buf_a_18_address1 <= zext_ln181_3_fu_529_p1(6 - 1 downto 0);
    block_buf_a_18_address2 <= zext_ln176_fu_499_p1(6 - 1 downto 0);
    block_buf_a_18_ce0 <= block_buf_a_18_ce0_local;

    block_buf_a_18_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            block_buf_a_18_ce0_local <= ap_const_logic_1;
        else 
            block_buf_a_18_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    block_buf_a_18_ce1 <= block_buf_a_18_ce1_local;

    block_buf_a_18_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            block_buf_a_18_ce1_local <= ap_const_logic_1;
        else 
            block_buf_a_18_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    block_buf_a_18_ce2 <= block_buf_a_18_ce2_local;

    block_buf_a_18_ce2_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            block_buf_a_18_ce2_local <= ap_const_logic_1;
        else 
            block_buf_a_18_ce2_local <= ap_const_logic_0;
        end if; 
    end process;

    block_buf_a_19_address0 <= zext_ln183_2_fu_563_p1(6 - 1 downto 0);
    block_buf_a_19_address1 <= zext_ln181_3_fu_529_p1(6 - 1 downto 0);
    block_buf_a_19_address2 <= zext_ln176_fu_499_p1(6 - 1 downto 0);
    block_buf_a_19_ce0 <= block_buf_a_19_ce0_local;

    block_buf_a_19_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            block_buf_a_19_ce0_local <= ap_const_logic_1;
        else 
            block_buf_a_19_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    block_buf_a_19_ce1 <= block_buf_a_19_ce1_local;

    block_buf_a_19_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            block_buf_a_19_ce1_local <= ap_const_logic_1;
        else 
            block_buf_a_19_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    block_buf_a_19_ce2 <= block_buf_a_19_ce2_local;

    block_buf_a_19_ce2_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            block_buf_a_19_ce2_local <= ap_const_logic_1;
        else 
            block_buf_a_19_ce2_local <= ap_const_logic_0;
        end if; 
    end process;

    gate_cache_address0 <= zext_ln185_fu_774_p1(13 - 1 downto 0);
    gate_cache_ce0 <= gate_cache_ce0_local;

    gate_cache_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then 
            gate_cache_ce0_local <= ap_const_logic_1;
        else 
            gate_cache_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_16169_p_ce <= ap_const_logic_1;
    grp_fu_16169_p_din0 <= tmp_s_fu_821_p19;
    grp_fu_16169_p_din1 <= mul42_i1_reg_1154;
    grp_fu_16169_p_opcode <= ap_const_lv2_0;
    grp_fu_16177_p_ce <= ap_const_logic_1;
    grp_fu_16177_p_din0 <= gate_cache_load_reg_1149;
    grp_fu_16177_p_din1 <= weight_reg_1144;
    grp_fu_16190_p_ce <= ap_const_logic_1;
    grp_fu_16190_p_din0 <= sext_ln184_fu_746_p1;
    grp_fu_16193_p_ce <= ap_const_logic_1;
    grp_fu_16193_p_din0 <= sext_ln184_2_fu_751_p1;
    grp_fu_2386_p_ce <= ap_const_logic_1;
    grp_fu_2386_p_din0 <= conv36_i1_reg_1119;
    grp_fu_2386_p_din1 <= conv37_i1_reg_1124;
    grp_fu_2390_p_ce <= ap_const_logic_1;
    grp_fu_2390_p_din0 <= mul_i2_reg_1129;
    grp_fu_2390_p_din1 <= d;
    icmp_ln174_fu_477_p2 <= "1" when (ap_sig_allocacmp_n = ap_const_lv9_100) else "0";
    lshr_ln176_1_fu_489_p4 <= ap_sig_allocacmp_n(7 downto 3);
    lshr_ln181_fu_691_p2 <= std_logic_vector(shift_right(unsigned(tmp_9_fu_663_p11),to_integer(unsigned('0' & zext_ln181_1_fu_687_p1(8-1 downto 0)))));
    n_3_fu_483_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_n) + unsigned(ap_const_lv9_1));
    or_ln5_fu_551_p3 <= (ap_const_lv1_1 & zext_ln183_fu_547_p1);
    q_fu_739_p4 <= ((xor_ln182_reg_1094 & trunc_ln182_reg_1099) & ql_val_reg_1089);
    qh_shift_fu_655_p3 <= (trunc_ln180_fu_652_p1 & ap_const_lv1_0);
    ql_val_fu_644_p3 <= 
        tmp_7_fu_630_p4 when (trunc_ln176_fu_576_p1(0) = '1') else 
        trunc_ln179_fu_640_p1;
    scale_fu_715_p10 <= n_reg_1014(5 downto 4);
    scale_fu_715_p9 <= "XXXXXXXX";
        sext_ln183_fu_559_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(or_ln5_fu_551_p3),6));

        sext_ln184_2_fu_751_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(scale_reg_1104),32));

        sext_ln184_fu_746_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(q_fu_739_p4),32));

    tmp_10_fu_507_p4 <= ap_sig_allocacmp_n(7 downto 4);
    tmp_11_fu_537_p4 <= ap_sig_allocacmp_n(7 downto 6);
    tmp_12_fu_758_p4 <= b_3(4 downto 1);
    tmp_7_fu_630_p4 <= tmp_8_fu_606_p11(7 downto 4);
    tmp_8_fu_606_p10 <= n_reg_1014(2 downto 1);
    tmp_8_fu_606_p9 <= "XXXXXXXX";
    tmp_9_fu_663_p10 <= n_reg_1014(3 downto 2);
    tmp_9_fu_663_p9 <= "XXXXXXXX";
    tmp_s_fu_821_p17 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    trunc_ln176_2_fu_755_p1 <= n_reg_1014_pp0_iter8_reg(3 - 1 downto 0);
    trunc_ln176_fu_576_p1 <= n_reg_1014(1 - 1 downto 0);
    trunc_ln179_fu_640_p1 <= tmp_8_fu_606_p11(4 - 1 downto 0);
    trunc_ln180_fu_652_p1 <= n_reg_1014(2 - 1 downto 0);
    trunc_ln182_fu_711_p1 <= lshr_ln181_fu_691_p2(1 - 1 downto 0);
    xor_ln182_fu_705_p2 <= (bit_sel_fu_697_p3 xor ap_const_lv1_1);
    zext_ln176_fu_499_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln176_1_fu_489_p4),64));
    zext_ln181_1_fu_687_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(qh_shift_fu_655_p3),8));
    zext_ln181_3_fu_529_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln181_cast_fu_521_p3),64));
    zext_ln181_cast_fu_521_p3 <= (ap_const_lv1_1 & zext_ln181_fu_517_p1);
    zext_ln181_fu_517_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_10_fu_507_p4),5));
    zext_ln183_2_fu_563_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln183_fu_559_p1),64));
    zext_ln183_fu_547_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_11_fu_537_p4),4));
    zext_ln185_fu_774_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln1_fu_767_p3),64));
end behav;
