-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity swiglu_swiglu_Pipeline_DECODE_MAC5 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    block_buf_b_8_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    block_buf_b_8_ce0 : OUT STD_LOGIC;
    block_buf_b_8_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    block_buf_b_9_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    block_buf_b_9_ce0 : OUT STD_LOGIC;
    block_buf_b_9_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    block_buf_b_10_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    block_buf_b_10_ce0 : OUT STD_LOGIC;
    block_buf_b_10_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    block_buf_b_11_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    block_buf_b_11_ce0 : OUT STD_LOGIC;
    block_buf_b_11_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    empty_25 : IN STD_LOGIC_VECTOR (5 downto 0);
    empty_26 : IN STD_LOGIC_VECTOR (5 downto 0);
    empty_27 : IN STD_LOGIC_VECTOR (5 downto 0);
    empty_28 : IN STD_LOGIC_VECTOR (5 downto 0);
    sc6_44 : IN STD_LOGIC_VECTOR (5 downto 0);
    sc6_39 : IN STD_LOGIC_VECTOR (5 downto 0);
    sc6_45 : IN STD_LOGIC_VECTOR (5 downto 0);
    sc6_46 : IN STD_LOGIC_VECTOR (5 downto 0);
    empty_29 : IN STD_LOGIC_VECTOR (5 downto 0);
    empty_30 : IN STD_LOGIC_VECTOR (5 downto 0);
    empty_31 : IN STD_LOGIC_VECTOR (5 downto 0);
    empty : IN STD_LOGIC_VECTOR (5 downto 0);
    mn6_43 : IN STD_LOGIC_VECTOR (5 downto 0);
    mn6_44 : IN STD_LOGIC_VECTOR (5 downto 0);
    mn6_45 : IN STD_LOGIC_VECTOR (5 downto 0);
    mn6_46 : IN STD_LOGIC_VECTOR (5 downto 0);
    or_ln2 : IN STD_LOGIC_VECTOR (12 downto 0);
    gate_cache_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    gate_cache_ce0 : OUT STD_LOGIC;
    gate_cache_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_w_40_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_w_40_load_out_ap_vld : OUT STD_LOGIC;
    acc_w_41_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_w_41_load_out_ap_vld : OUT STD_LOGIC;
    acc_w_42_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_w_42_load_out_ap_vld : OUT STD_LOGIC;
    acc_w_43_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_w_43_load_out_ap_vld : OUT STD_LOGIC;
    acc_w_44_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_w_44_load_out_ap_vld : OUT STD_LOGIC;
    acc_w_45_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_w_45_load_out_ap_vld : OUT STD_LOGIC;
    acc_w_46_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_w_46_load_out_ap_vld : OUT STD_LOGIC;
    acc_w_47_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_w_47_load_out_ap_vld : OUT STD_LOGIC;
    acc_m_40_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_m_40_load_out_ap_vld : OUT STD_LOGIC;
    acc_m_41_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_m_41_load_out_ap_vld : OUT STD_LOGIC;
    acc_m_42_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_m_42_load_out_ap_vld : OUT STD_LOGIC;
    acc_m_43_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_m_43_load_out_ap_vld : OUT STD_LOGIC;
    acc_m_44_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_m_44_load_out_ap_vld : OUT STD_LOGIC;
    acc_m_45_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_m_45_load_out_ap_vld : OUT STD_LOGIC;
    acc_m_46_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_m_46_load_out_ap_vld : OUT STD_LOGIC;
    acc_m_47_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_m_47_load_out_ap_vld : OUT STD_LOGIC;
    grp_fu_16169_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16169_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16169_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_16169_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16169_p_ce : OUT STD_LOGIC;
    grp_fu_16173_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16173_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16173_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_16173_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16173_p_ce : OUT STD_LOGIC;
    grp_fu_2386_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2386_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2386_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2386_p_ce : OUT STD_LOGIC;
    grp_fu_2390_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2390_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2390_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2390_p_ce : OUT STD_LOGIC;
    grp_fu_16177_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16177_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16177_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16177_p_ce : OUT STD_LOGIC;
    grp_fu_16181_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16181_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16181_p_ce : OUT STD_LOGIC;
    grp_fu_16184_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16184_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16184_p_ce : OUT STD_LOGIC;
    grp_fu_16187_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16187_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_16187_p_ce : OUT STD_LOGIC );
end;


architecture behav of swiglu_swiglu_Pipeline_DECODE_MAC5 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv9_100 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv6_4 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln126_fu_636_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal n_4_reg_1349 : STD_LOGIC_VECTOR (8 downto 0);
    signal n_4_reg_1349_pp0_iter1_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal n_4_reg_1349_pp0_iter2_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln126_reg_1358 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln126_reg_1358_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln126_reg_1358_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln126_reg_1358_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln126_reg_1358_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln126_reg_1358_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln126_reg_1358_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln126_reg_1358_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln126_reg_1358_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln126_reg_1358_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln126_reg_1358_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln126_reg_1358_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln126_reg_1358_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln129_s_reg_1382 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln129_s_reg_1382_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln129_s_reg_1382_pp0_iter3_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal nibble_fu_744_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal nibble_reg_1387 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_15_fu_748_p19 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_15_reg_1392 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln133_fu_780_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln135_fu_784_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln129_fu_791_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln129_reg_1407 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln129_reg_1407_pp0_iter4_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln129_reg_1407_pp0_iter5_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln129_reg_1407_pp0_iter6_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln129_reg_1407_pp0_iter7_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln129_reg_1407_pp0_iter8_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln129_reg_1407_pp0_iter9_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln129_reg_1407_pp0_iter10_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln129_reg_1407_pp0_iter11_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln129_reg_1407_pp0_iter12_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln129_reg_1407_pp0_iter13_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_14_fu_822_p19 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_14_reg_1418 : STD_LOGIC_VECTOR (5 downto 0);
    signal mn_reg_1423 : STD_LOGIC_VECTOR (31 downto 0);
    signal v_reg_1428 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv168_i_reg_1434 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln132_fu_853_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sc_reg_1444 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_i7_reg_1449 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul174_i_reg_1454 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_17_fu_881_p19 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul169_i_reg_1464 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_16_fu_945_p19 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln131_1_fu_668_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln134_fu_799_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal n_fu_172 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal add_ln126_fu_642_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_n_4 : STD_LOGIC_VECTOR (8 downto 0);
    signal acc_m_7_fu_176 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_m_7_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal acc_m_6_fu_180 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_m_6_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_m_5_fu_184 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_m_5_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_m_4_fu_188 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_m_4_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_m_3_fu_192 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_m_3_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_m_2_fu_196 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_m_2_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_m_1_fu_200 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_m_1_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_m_fu_204 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_m_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_w_7_fu_208 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_w_7_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_w_6_fu_212 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_w_6_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_w_5_fu_216 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_w_5_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_w_4_fu_220 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_w_4_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_w_3_fu_224 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_w_3_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_w_2_fu_228 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_w_2_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_w_1_fu_232 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_w_1_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_w_fu_236 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_w_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal block_buf_b_8_ce0_local : STD_LOGIC;
    signal block_buf_b_9_ce0_local : STD_LOGIC;
    signal block_buf_b_10_ce0_local : STD_LOGIC;
    signal block_buf_b_11_ce0_local : STD_LOGIC;
    signal gate_cache_ce0_local : STD_LOGIC;
    signal tmp_s_fu_648_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln131_fu_658_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln131_fu_662_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_13_fu_699_p9 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_13_fu_699_p10 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln131_fu_723_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln131_5_fu_726_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_13_fu_699_p11 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln131_2_fu_734_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal lshr_ln131_fu_738_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_15_fu_748_p17 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_15_fu_748_p18 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln126_fu_788_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln134_fu_794_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_14_fu_822_p17 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_fu_881_p17 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_16_fu_945_p17 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal tmp_13_fu_699_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_13_fu_699_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_13_fu_699_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_13_fu_699_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_15_fu_748_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_15_fu_748_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_15_fu_748_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_15_fu_748_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_15_fu_748_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_15_fu_748_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_15_fu_748_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_15_fu_748_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_14_fu_822_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_14_fu_822_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_14_fu_822_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_14_fu_822_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_14_fu_822_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_14_fu_822_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_14_fu_822_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_14_fu_822_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_17_fu_881_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_17_fu_881_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_17_fu_881_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_17_fu_881_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_17_fu_881_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_17_fu_881_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_17_fu_881_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_17_fu_881_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_16_fu_945_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_16_fu_945_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_16_fu_945_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_16_fu_945_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_16_fu_945_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_16_fu_945_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_16_fu_945_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_16_fu_945_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component swiglu_fadd_32ns_32ns_32_4_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component swiglu_fmul_32ns_32ns_32_3_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component swiglu_uitofp_32ns_32_3_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component swiglu_sparsemux_9_2_8_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (1 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (7 downto 0);
        def : IN STD_LOGIC_VECTOR (7 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component swiglu_sparsemux_17_3_6_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (2 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (2 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (2 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (2 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (2 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (2 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (2 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (2 downto 0);
        din7_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (5 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        din2 : IN STD_LOGIC_VECTOR (5 downto 0);
        din3 : IN STD_LOGIC_VECTOR (5 downto 0);
        din4 : IN STD_LOGIC_VECTOR (5 downto 0);
        din5 : IN STD_LOGIC_VECTOR (5 downto 0);
        din6 : IN STD_LOGIC_VECTOR (5 downto 0);
        din7 : IN STD_LOGIC_VECTOR (5 downto 0);
        def : IN STD_LOGIC_VECTOR (5 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (5 downto 0) );
    end component;


    component swiglu_sparsemux_17_3_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (2 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (2 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (2 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (2 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (2 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (2 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (2 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (2 downto 0);
        din7_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (31 downto 0);
        din7 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component swiglu_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_9_2_8_1_1_U378 : component swiglu_sparsemux_9_2_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 8,
        CASE1 => "01",
        din1_WIDTH => 8,
        CASE2 => "10",
        din2_WIDTH => 8,
        CASE3 => "11",
        din3_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => block_buf_b_8_q0,
        din1 => block_buf_b_9_q0,
        din2 => block_buf_b_10_q0,
        din3 => block_buf_b_11_q0,
        def => tmp_13_fu_699_p9,
        sel => tmp_13_fu_699_p10,
        dout => tmp_13_fu_699_p11);

    sparsemux_17_3_6_1_1_U379 : component swiglu_sparsemux_17_3_6_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 6,
        CASE1 => "001",
        din1_WIDTH => 6,
        CASE2 => "010",
        din2_WIDTH => 6,
        CASE3 => "011",
        din3_WIDTH => 6,
        CASE4 => "100",
        din4_WIDTH => 6,
        CASE5 => "101",
        din5_WIDTH => 6,
        CASE6 => "110",
        din6_WIDTH => 6,
        CASE7 => "111",
        din7_WIDTH => 6,
        def_WIDTH => 6,
        sel_WIDTH => 3,
        dout_WIDTH => 6)
    port map (
        din0 => empty_29,
        din1 => empty_30,
        din2 => empty_31,
        din3 => empty,
        din4 => mn6_43,
        din5 => mn6_44,
        din6 => mn6_45,
        din7 => mn6_46,
        def => tmp_15_fu_748_p17,
        sel => tmp_15_fu_748_p18,
        dout => tmp_15_fu_748_p19);

    sparsemux_17_3_6_1_1_U380 : component swiglu_sparsemux_17_3_6_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 6,
        CASE1 => "001",
        din1_WIDTH => 6,
        CASE2 => "010",
        din2_WIDTH => 6,
        CASE3 => "011",
        din3_WIDTH => 6,
        CASE4 => "100",
        din4_WIDTH => 6,
        CASE5 => "101",
        din5_WIDTH => 6,
        CASE6 => "110",
        din6_WIDTH => 6,
        CASE7 => "111",
        din7_WIDTH => 6,
        def_WIDTH => 6,
        sel_WIDTH => 3,
        dout_WIDTH => 6)
    port map (
        din0 => empty_25,
        din1 => empty_26,
        din2 => empty_27,
        din3 => empty_28,
        din4 => sc6_44,
        din5 => sc6_39,
        din6 => sc6_45,
        din7 => sc6_46,
        def => tmp_14_fu_822_p17,
        sel => trunc_ln129_s_reg_1382_pp0_iter3_reg,
        dout => tmp_14_fu_822_p19);

    sparsemux_17_3_32_1_1_U381 : component swiglu_sparsemux_17_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 32,
        CASE1 => "001",
        din1_WIDTH => 32,
        CASE2 => "010",
        din2_WIDTH => 32,
        CASE3 => "011",
        din3_WIDTH => 32,
        CASE4 => "100",
        din4_WIDTH => 32,
        CASE5 => "101",
        din5_WIDTH => 32,
        CASE6 => "110",
        din6_WIDTH => 32,
        CASE7 => "111",
        din7_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => ap_sig_allocacmp_acc_m_load_1,
        din1 => ap_sig_allocacmp_acc_m_1_load_1,
        din2 => ap_sig_allocacmp_acc_m_2_load_1,
        din3 => ap_sig_allocacmp_acc_m_3_load_1,
        din4 => ap_sig_allocacmp_acc_m_4_load_1,
        din5 => ap_sig_allocacmp_acc_m_5_load_1,
        din6 => ap_sig_allocacmp_acc_m_6_load_1,
        din7 => ap_sig_allocacmp_acc_m_7_load_1,
        def => tmp_17_fu_881_p17,
        sel => trunc_ln129_reg_1407_pp0_iter7_reg,
        dout => tmp_17_fu_881_p19);

    sparsemux_17_3_32_1_1_U382 : component swiglu_sparsemux_17_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 32,
        CASE1 => "001",
        din1_WIDTH => 32,
        CASE2 => "010",
        din2_WIDTH => 32,
        CASE3 => "011",
        din3_WIDTH => 32,
        CASE4 => "100",
        din4_WIDTH => 32,
        CASE5 => "101",
        din5_WIDTH => 32,
        CASE6 => "110",
        din6_WIDTH => 32,
        CASE7 => "111",
        din7_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => ap_sig_allocacmp_acc_w_load_1,
        din1 => ap_sig_allocacmp_acc_w_1_load_1,
        din2 => ap_sig_allocacmp_acc_w_2_load_1,
        din3 => ap_sig_allocacmp_acc_w_3_load_1,
        din4 => ap_sig_allocacmp_acc_w_4_load_1,
        din5 => ap_sig_allocacmp_acc_w_5_load_1,
        din6 => ap_sig_allocacmp_acc_w_6_load_1,
        din7 => ap_sig_allocacmp_acc_w_7_load_1,
        def => tmp_16_fu_945_p17,
        sel => trunc_ln129_reg_1407_pp0_iter10_reg,
        dout => tmp_16_fu_945_p19);

    flow_control_loop_pipe_sequential_init_U : component swiglu_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    acc_m_1_fu_200_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_m_1_fu_200 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln129_reg_1407_pp0_iter10_reg = ap_const_lv3_1))) then 
                    acc_m_1_fu_200 <= grp_fu_16169_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    acc_m_2_fu_196_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_m_2_fu_196 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln129_reg_1407_pp0_iter10_reg = ap_const_lv3_2))) then 
                    acc_m_2_fu_196 <= grp_fu_16169_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    acc_m_3_fu_192_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_m_3_fu_192 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln129_reg_1407_pp0_iter10_reg = ap_const_lv3_3))) then 
                    acc_m_3_fu_192 <= grp_fu_16169_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    acc_m_4_fu_188_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_m_4_fu_188 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln129_reg_1407_pp0_iter10_reg = ap_const_lv3_4))) then 
                    acc_m_4_fu_188 <= grp_fu_16169_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    acc_m_5_fu_184_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_m_5_fu_184 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln129_reg_1407_pp0_iter10_reg = ap_const_lv3_5))) then 
                    acc_m_5_fu_184 <= grp_fu_16169_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    acc_m_6_fu_180_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_m_6_fu_180 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln129_reg_1407_pp0_iter10_reg = ap_const_lv3_6))) then 
                    acc_m_6_fu_180 <= grp_fu_16169_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    acc_m_7_fu_176_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_m_7_fu_176 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln129_reg_1407_pp0_iter10_reg = ap_const_lv3_7))) then 
                    acc_m_7_fu_176 <= grp_fu_16169_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    acc_m_fu_204_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_m_fu_204 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln129_reg_1407_pp0_iter10_reg = ap_const_lv3_0))) then 
                    acc_m_fu_204 <= grp_fu_16169_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    acc_w_1_fu_232_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_w_1_fu_232 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln129_reg_1407_pp0_iter13_reg = ap_const_lv3_1))) then 
                    acc_w_1_fu_232 <= grp_fu_16173_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    acc_w_2_fu_228_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_w_2_fu_228 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln129_reg_1407_pp0_iter13_reg = ap_const_lv3_2))) then 
                    acc_w_2_fu_228 <= grp_fu_16173_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    acc_w_3_fu_224_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_w_3_fu_224 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln129_reg_1407_pp0_iter13_reg = ap_const_lv3_3))) then 
                    acc_w_3_fu_224 <= grp_fu_16173_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    acc_w_4_fu_220_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_w_4_fu_220 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln129_reg_1407_pp0_iter13_reg = ap_const_lv3_4))) then 
                    acc_w_4_fu_220 <= grp_fu_16173_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    acc_w_5_fu_216_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_w_5_fu_216 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln129_reg_1407_pp0_iter13_reg = ap_const_lv3_5))) then 
                    acc_w_5_fu_216 <= grp_fu_16173_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    acc_w_6_fu_212_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_w_6_fu_212 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln129_reg_1407_pp0_iter13_reg = ap_const_lv3_6))) then 
                    acc_w_6_fu_212 <= grp_fu_16173_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    acc_w_7_fu_208_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_w_7_fu_208 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln129_reg_1407_pp0_iter13_reg = ap_const_lv3_7))) then 
                    acc_w_7_fu_208 <= grp_fu_16173_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    acc_w_fu_236_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_w_fu_236 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln129_reg_1407_pp0_iter13_reg = ap_const_lv3_0))) then 
                    acc_w_fu_236 <= grp_fu_16173_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    n_fu_172_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln126_fu_636_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    n_fu_172 <= add_ln126_fu_642_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    n_fu_172 <= ap_const_lv9_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                conv168_i_reg_1434 <= grp_fu_16184_p_dout0;
                icmp_ln126_reg_1358_pp0_iter10_reg <= icmp_ln126_reg_1358_pp0_iter9_reg;
                icmp_ln126_reg_1358_pp0_iter11_reg <= icmp_ln126_reg_1358_pp0_iter10_reg;
                icmp_ln126_reg_1358_pp0_iter12_reg <= icmp_ln126_reg_1358_pp0_iter11_reg;
                icmp_ln126_reg_1358_pp0_iter2_reg <= icmp_ln126_reg_1358_pp0_iter1_reg;
                icmp_ln126_reg_1358_pp0_iter3_reg <= icmp_ln126_reg_1358_pp0_iter2_reg;
                icmp_ln126_reg_1358_pp0_iter4_reg <= icmp_ln126_reg_1358_pp0_iter3_reg;
                icmp_ln126_reg_1358_pp0_iter5_reg <= icmp_ln126_reg_1358_pp0_iter4_reg;
                icmp_ln126_reg_1358_pp0_iter6_reg <= icmp_ln126_reg_1358_pp0_iter5_reg;
                icmp_ln126_reg_1358_pp0_iter7_reg <= icmp_ln126_reg_1358_pp0_iter6_reg;
                icmp_ln126_reg_1358_pp0_iter8_reg <= icmp_ln126_reg_1358_pp0_iter7_reg;
                icmp_ln126_reg_1358_pp0_iter9_reg <= icmp_ln126_reg_1358_pp0_iter8_reg;
                mn_reg_1423 <= grp_fu_16181_p_dout0;
                mul169_i_reg_1464 <= grp_fu_16177_p_dout0;
                mul174_i_reg_1454 <= grp_fu_2390_p_dout0;
                mul_i7_reg_1449 <= grp_fu_2386_p_dout0;
                n_4_reg_1349_pp0_iter2_reg <= n_4_reg_1349_pp0_iter1_reg;
                sc_reg_1444 <= grp_fu_16187_p_dout0;
                tmp_14_reg_1418 <= tmp_14_fu_822_p19;
                trunc_ln129_reg_1407 <= trunc_ln129_fu_791_p1;
                trunc_ln129_reg_1407_pp0_iter10_reg <= trunc_ln129_reg_1407_pp0_iter9_reg;
                trunc_ln129_reg_1407_pp0_iter11_reg <= trunc_ln129_reg_1407_pp0_iter10_reg;
                trunc_ln129_reg_1407_pp0_iter12_reg <= trunc_ln129_reg_1407_pp0_iter11_reg;
                trunc_ln129_reg_1407_pp0_iter13_reg <= trunc_ln129_reg_1407_pp0_iter12_reg;
                trunc_ln129_reg_1407_pp0_iter4_reg <= trunc_ln129_reg_1407;
                trunc_ln129_reg_1407_pp0_iter5_reg <= trunc_ln129_reg_1407_pp0_iter4_reg;
                trunc_ln129_reg_1407_pp0_iter6_reg <= trunc_ln129_reg_1407_pp0_iter5_reg;
                trunc_ln129_reg_1407_pp0_iter7_reg <= trunc_ln129_reg_1407_pp0_iter6_reg;
                trunc_ln129_reg_1407_pp0_iter8_reg <= trunc_ln129_reg_1407_pp0_iter7_reg;
                trunc_ln129_reg_1407_pp0_iter9_reg <= trunc_ln129_reg_1407_pp0_iter8_reg;
                trunc_ln129_s_reg_1382_pp0_iter2_reg <= trunc_ln129_s_reg_1382;
                trunc_ln129_s_reg_1382_pp0_iter3_reg <= trunc_ln129_s_reg_1382_pp0_iter2_reg;
                v_reg_1428 <= gate_cache_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln126_reg_1358 <= icmp_ln126_fu_636_p2;
                icmp_ln126_reg_1358_pp0_iter1_reg <= icmp_ln126_reg_1358;
                n_4_reg_1349 <= ap_sig_allocacmp_n_4;
                n_4_reg_1349_pp0_iter1_reg <= n_4_reg_1349;
                nibble_reg_1387 <= nibble_fu_744_p1;
                tmp_15_reg_1392 <= tmp_15_fu_748_p19;
                trunc_ln129_s_reg_1382 <= n_4_reg_1349(7 downto 5);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    acc_m_40_load_out <= acc_m_fu_204;

    acc_m_40_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln126_reg_1358_pp0_iter12_reg, ap_loop_exit_ready_pp0_iter13_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (icmp_ln126_reg_1358_pp0_iter12_reg = ap_const_lv1_1))) then 
            acc_m_40_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_m_40_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_m_41_load_out <= acc_m_1_fu_200;

    acc_m_41_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln126_reg_1358_pp0_iter12_reg, ap_loop_exit_ready_pp0_iter13_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (icmp_ln126_reg_1358_pp0_iter12_reg = ap_const_lv1_1))) then 
            acc_m_41_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_m_41_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_m_42_load_out <= acc_m_2_fu_196;

    acc_m_42_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln126_reg_1358_pp0_iter12_reg, ap_loop_exit_ready_pp0_iter13_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (icmp_ln126_reg_1358_pp0_iter12_reg = ap_const_lv1_1))) then 
            acc_m_42_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_m_42_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_m_43_load_out <= acc_m_3_fu_192;

    acc_m_43_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln126_reg_1358_pp0_iter12_reg, ap_loop_exit_ready_pp0_iter13_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (icmp_ln126_reg_1358_pp0_iter12_reg = ap_const_lv1_1))) then 
            acc_m_43_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_m_43_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_m_44_load_out <= acc_m_4_fu_188;

    acc_m_44_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln126_reg_1358_pp0_iter12_reg, ap_loop_exit_ready_pp0_iter13_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (icmp_ln126_reg_1358_pp0_iter12_reg = ap_const_lv1_1))) then 
            acc_m_44_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_m_44_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_m_45_load_out <= acc_m_5_fu_184;

    acc_m_45_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln126_reg_1358_pp0_iter12_reg, ap_loop_exit_ready_pp0_iter13_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (icmp_ln126_reg_1358_pp0_iter12_reg = ap_const_lv1_1))) then 
            acc_m_45_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_m_45_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_m_46_load_out <= acc_m_6_fu_180;

    acc_m_46_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln126_reg_1358_pp0_iter12_reg, ap_loop_exit_ready_pp0_iter13_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (icmp_ln126_reg_1358_pp0_iter12_reg = ap_const_lv1_1))) then 
            acc_m_46_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_m_46_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_m_47_load_out <= acc_m_7_fu_176;

    acc_m_47_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln126_reg_1358_pp0_iter12_reg, ap_loop_exit_ready_pp0_iter13_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (icmp_ln126_reg_1358_pp0_iter12_reg = ap_const_lv1_1))) then 
            acc_m_47_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_m_47_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_w_40_load_out <= acc_w_fu_236;

    acc_w_40_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln126_reg_1358_pp0_iter12_reg, ap_loop_exit_ready_pp0_iter13_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (icmp_ln126_reg_1358_pp0_iter12_reg = ap_const_lv1_1))) then 
            acc_w_40_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_w_40_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_w_41_load_out <= acc_w_1_fu_232;

    acc_w_41_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln126_reg_1358_pp0_iter12_reg, ap_loop_exit_ready_pp0_iter13_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (icmp_ln126_reg_1358_pp0_iter12_reg = ap_const_lv1_1))) then 
            acc_w_41_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_w_41_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_w_42_load_out <= acc_w_2_fu_228;

    acc_w_42_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln126_reg_1358_pp0_iter12_reg, ap_loop_exit_ready_pp0_iter13_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (icmp_ln126_reg_1358_pp0_iter12_reg = ap_const_lv1_1))) then 
            acc_w_42_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_w_42_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_w_43_load_out <= acc_w_3_fu_224;

    acc_w_43_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln126_reg_1358_pp0_iter12_reg, ap_loop_exit_ready_pp0_iter13_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (icmp_ln126_reg_1358_pp0_iter12_reg = ap_const_lv1_1))) then 
            acc_w_43_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_w_43_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_w_44_load_out <= acc_w_4_fu_220;

    acc_w_44_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln126_reg_1358_pp0_iter12_reg, ap_loop_exit_ready_pp0_iter13_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (icmp_ln126_reg_1358_pp0_iter12_reg = ap_const_lv1_1))) then 
            acc_w_44_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_w_44_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_w_45_load_out <= acc_w_5_fu_216;

    acc_w_45_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln126_reg_1358_pp0_iter12_reg, ap_loop_exit_ready_pp0_iter13_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (icmp_ln126_reg_1358_pp0_iter12_reg = ap_const_lv1_1))) then 
            acc_w_45_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_w_45_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_w_46_load_out <= acc_w_6_fu_212;

    acc_w_46_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln126_reg_1358_pp0_iter12_reg, ap_loop_exit_ready_pp0_iter13_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (icmp_ln126_reg_1358_pp0_iter12_reg = ap_const_lv1_1))) then 
            acc_w_46_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_w_46_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_w_47_load_out <= acc_w_7_fu_208;

    acc_w_47_load_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln126_reg_1358_pp0_iter12_reg, ap_loop_exit_ready_pp0_iter13_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (icmp_ln126_reg_1358_pp0_iter12_reg = ap_const_lv1_1))) then 
            acc_w_47_load_out_ap_vld <= ap_const_logic_1;
        else 
            acc_w_47_load_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln126_fu_642_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_n_4) + unsigned(ap_const_lv9_1));
    add_ln131_fu_662_p2 <= std_logic_vector(unsigned(zext_ln131_fu_658_p1) + unsigned(ap_const_lv6_4));
    add_ln134_fu_794_p2 <= std_logic_vector(unsigned(zext_ln126_fu_788_p1) + unsigned(or_ln2));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln126_fu_636_p2)
    begin
        if (((icmp_ln126_fu_636_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter13_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_acc_m_1_load_1_assign_proc : process(ap_enable_reg_pp0_iter11, trunc_ln129_reg_1407_pp0_iter10_reg, ap_block_pp0_stage0, acc_m_1_fu_200, grp_fu_16169_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln129_reg_1407_pp0_iter10_reg = ap_const_lv3_1))) then 
            ap_sig_allocacmp_acc_m_1_load_1 <= grp_fu_16169_p_dout0;
        else 
            ap_sig_allocacmp_acc_m_1_load_1 <= acc_m_1_fu_200;
        end if; 
    end process;


    ap_sig_allocacmp_acc_m_2_load_1_assign_proc : process(ap_enable_reg_pp0_iter11, trunc_ln129_reg_1407_pp0_iter10_reg, ap_block_pp0_stage0, acc_m_2_fu_196, grp_fu_16169_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln129_reg_1407_pp0_iter10_reg = ap_const_lv3_2))) then 
            ap_sig_allocacmp_acc_m_2_load_1 <= grp_fu_16169_p_dout0;
        else 
            ap_sig_allocacmp_acc_m_2_load_1 <= acc_m_2_fu_196;
        end if; 
    end process;


    ap_sig_allocacmp_acc_m_3_load_1_assign_proc : process(ap_enable_reg_pp0_iter11, trunc_ln129_reg_1407_pp0_iter10_reg, ap_block_pp0_stage0, acc_m_3_fu_192, grp_fu_16169_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln129_reg_1407_pp0_iter10_reg = ap_const_lv3_3))) then 
            ap_sig_allocacmp_acc_m_3_load_1 <= grp_fu_16169_p_dout0;
        else 
            ap_sig_allocacmp_acc_m_3_load_1 <= acc_m_3_fu_192;
        end if; 
    end process;


    ap_sig_allocacmp_acc_m_4_load_1_assign_proc : process(ap_enable_reg_pp0_iter11, trunc_ln129_reg_1407_pp0_iter10_reg, ap_block_pp0_stage0, acc_m_4_fu_188, grp_fu_16169_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln129_reg_1407_pp0_iter10_reg = ap_const_lv3_4))) then 
            ap_sig_allocacmp_acc_m_4_load_1 <= grp_fu_16169_p_dout0;
        else 
            ap_sig_allocacmp_acc_m_4_load_1 <= acc_m_4_fu_188;
        end if; 
    end process;


    ap_sig_allocacmp_acc_m_5_load_1_assign_proc : process(ap_enable_reg_pp0_iter11, trunc_ln129_reg_1407_pp0_iter10_reg, ap_block_pp0_stage0, acc_m_5_fu_184, grp_fu_16169_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln129_reg_1407_pp0_iter10_reg = ap_const_lv3_5))) then 
            ap_sig_allocacmp_acc_m_5_load_1 <= grp_fu_16169_p_dout0;
        else 
            ap_sig_allocacmp_acc_m_5_load_1 <= acc_m_5_fu_184;
        end if; 
    end process;


    ap_sig_allocacmp_acc_m_6_load_1_assign_proc : process(ap_enable_reg_pp0_iter11, trunc_ln129_reg_1407_pp0_iter10_reg, ap_block_pp0_stage0, acc_m_6_fu_180, grp_fu_16169_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln129_reg_1407_pp0_iter10_reg = ap_const_lv3_6))) then 
            ap_sig_allocacmp_acc_m_6_load_1 <= grp_fu_16169_p_dout0;
        else 
            ap_sig_allocacmp_acc_m_6_load_1 <= acc_m_6_fu_180;
        end if; 
    end process;


    ap_sig_allocacmp_acc_m_7_load_1_assign_proc : process(ap_enable_reg_pp0_iter11, trunc_ln129_reg_1407_pp0_iter10_reg, ap_block_pp0_stage0, acc_m_7_fu_176, grp_fu_16169_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln129_reg_1407_pp0_iter10_reg = ap_const_lv3_7))) then 
            ap_sig_allocacmp_acc_m_7_load_1 <= grp_fu_16169_p_dout0;
        else 
            ap_sig_allocacmp_acc_m_7_load_1 <= acc_m_7_fu_176;
        end if; 
    end process;


    ap_sig_allocacmp_acc_m_load_1_assign_proc : process(ap_enable_reg_pp0_iter11, trunc_ln129_reg_1407_pp0_iter10_reg, ap_block_pp0_stage0, acc_m_fu_204, grp_fu_16169_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln129_reg_1407_pp0_iter10_reg = ap_const_lv3_0))) then 
            ap_sig_allocacmp_acc_m_load_1 <= grp_fu_16169_p_dout0;
        else 
            ap_sig_allocacmp_acc_m_load_1 <= acc_m_fu_204;
        end if; 
    end process;


    ap_sig_allocacmp_acc_w_1_load_1_assign_proc : process(ap_enable_reg_pp0_iter14, trunc_ln129_reg_1407_pp0_iter13_reg, ap_block_pp0_stage0, acc_w_1_fu_232, grp_fu_16173_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln129_reg_1407_pp0_iter13_reg = ap_const_lv3_1))) then 
            ap_sig_allocacmp_acc_w_1_load_1 <= grp_fu_16173_p_dout0;
        else 
            ap_sig_allocacmp_acc_w_1_load_1 <= acc_w_1_fu_232;
        end if; 
    end process;


    ap_sig_allocacmp_acc_w_2_load_1_assign_proc : process(ap_enable_reg_pp0_iter14, trunc_ln129_reg_1407_pp0_iter13_reg, ap_block_pp0_stage0, acc_w_2_fu_228, grp_fu_16173_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln129_reg_1407_pp0_iter13_reg = ap_const_lv3_2))) then 
            ap_sig_allocacmp_acc_w_2_load_1 <= grp_fu_16173_p_dout0;
        else 
            ap_sig_allocacmp_acc_w_2_load_1 <= acc_w_2_fu_228;
        end if; 
    end process;


    ap_sig_allocacmp_acc_w_3_load_1_assign_proc : process(ap_enable_reg_pp0_iter14, trunc_ln129_reg_1407_pp0_iter13_reg, ap_block_pp0_stage0, acc_w_3_fu_224, grp_fu_16173_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln129_reg_1407_pp0_iter13_reg = ap_const_lv3_3))) then 
            ap_sig_allocacmp_acc_w_3_load_1 <= grp_fu_16173_p_dout0;
        else 
            ap_sig_allocacmp_acc_w_3_load_1 <= acc_w_3_fu_224;
        end if; 
    end process;


    ap_sig_allocacmp_acc_w_4_load_1_assign_proc : process(ap_enable_reg_pp0_iter14, trunc_ln129_reg_1407_pp0_iter13_reg, ap_block_pp0_stage0, acc_w_4_fu_220, grp_fu_16173_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln129_reg_1407_pp0_iter13_reg = ap_const_lv3_4))) then 
            ap_sig_allocacmp_acc_w_4_load_1 <= grp_fu_16173_p_dout0;
        else 
            ap_sig_allocacmp_acc_w_4_load_1 <= acc_w_4_fu_220;
        end if; 
    end process;


    ap_sig_allocacmp_acc_w_5_load_1_assign_proc : process(ap_enable_reg_pp0_iter14, trunc_ln129_reg_1407_pp0_iter13_reg, ap_block_pp0_stage0, acc_w_5_fu_216, grp_fu_16173_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln129_reg_1407_pp0_iter13_reg = ap_const_lv3_5))) then 
            ap_sig_allocacmp_acc_w_5_load_1 <= grp_fu_16173_p_dout0;
        else 
            ap_sig_allocacmp_acc_w_5_load_1 <= acc_w_5_fu_216;
        end if; 
    end process;


    ap_sig_allocacmp_acc_w_6_load_1_assign_proc : process(ap_enable_reg_pp0_iter14, trunc_ln129_reg_1407_pp0_iter13_reg, ap_block_pp0_stage0, acc_w_6_fu_212, grp_fu_16173_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln129_reg_1407_pp0_iter13_reg = ap_const_lv3_6))) then 
            ap_sig_allocacmp_acc_w_6_load_1 <= grp_fu_16173_p_dout0;
        else 
            ap_sig_allocacmp_acc_w_6_load_1 <= acc_w_6_fu_212;
        end if; 
    end process;


    ap_sig_allocacmp_acc_w_7_load_1_assign_proc : process(ap_enable_reg_pp0_iter14, trunc_ln129_reg_1407_pp0_iter13_reg, ap_block_pp0_stage0, acc_w_7_fu_208, grp_fu_16173_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln129_reg_1407_pp0_iter13_reg = ap_const_lv3_7))) then 
            ap_sig_allocacmp_acc_w_7_load_1 <= grp_fu_16173_p_dout0;
        else 
            ap_sig_allocacmp_acc_w_7_load_1 <= acc_w_7_fu_208;
        end if; 
    end process;


    ap_sig_allocacmp_acc_w_load_1_assign_proc : process(ap_enable_reg_pp0_iter14, trunc_ln129_reg_1407_pp0_iter13_reg, ap_block_pp0_stage0, acc_w_fu_236, grp_fu_16173_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln129_reg_1407_pp0_iter13_reg = ap_const_lv3_0))) then 
            ap_sig_allocacmp_acc_w_load_1 <= grp_fu_16173_p_dout0;
        else 
            ap_sig_allocacmp_acc_w_load_1 <= acc_w_fu_236;
        end if; 
    end process;


    ap_sig_allocacmp_n_4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, n_fu_172, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_n_4 <= ap_const_lv9_0;
        else 
            ap_sig_allocacmp_n_4 <= n_fu_172;
        end if; 
    end process;

    block_buf_b_10_address0 <= zext_ln131_1_fu_668_p1(6 - 1 downto 0);
    block_buf_b_10_ce0 <= block_buf_b_10_ce0_local;

    block_buf_b_10_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            block_buf_b_10_ce0_local <= ap_const_logic_1;
        else 
            block_buf_b_10_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    block_buf_b_11_address0 <= zext_ln131_1_fu_668_p1(6 - 1 downto 0);
    block_buf_b_11_ce0 <= block_buf_b_11_ce0_local;

    block_buf_b_11_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            block_buf_b_11_ce0_local <= ap_const_logic_1;
        else 
            block_buf_b_11_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    block_buf_b_8_address0 <= zext_ln131_1_fu_668_p1(6 - 1 downto 0);
    block_buf_b_8_ce0 <= block_buf_b_8_ce0_local;

    block_buf_b_8_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            block_buf_b_8_ce0_local <= ap_const_logic_1;
        else 
            block_buf_b_8_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    block_buf_b_9_address0 <= zext_ln131_1_fu_668_p1(6 - 1 downto 0);
    block_buf_b_9_ce0 <= block_buf_b_9_ce0_local;

    block_buf_b_9_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            block_buf_b_9_ce0_local <= ap_const_logic_1;
        else 
            block_buf_b_9_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    gate_cache_address0 <= zext_ln134_fu_799_p1(13 - 1 downto 0);
    gate_cache_ce0 <= gate_cache_ce0_local;

    gate_cache_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            gate_cache_ce0_local <= ap_const_logic_1;
        else 
            gate_cache_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_16169_p_ce <= ap_const_logic_1;
    grp_fu_16169_p_din0 <= tmp_17_fu_881_p19;
    grp_fu_16169_p_din1 <= mul174_i_reg_1454;
    grp_fu_16169_p_opcode <= ap_const_lv2_0;
    grp_fu_16173_p_ce <= ap_const_logic_1;
    grp_fu_16173_p_din0 <= tmp_16_fu_945_p19;
    grp_fu_16173_p_din1 <= mul169_i_reg_1464;
    grp_fu_16173_p_opcode <= ap_const_lv2_0;
    grp_fu_16177_p_ce <= ap_const_logic_1;
    grp_fu_16177_p_din0 <= mul_i7_reg_1449;
    grp_fu_16177_p_din1 <= sc_reg_1444;
    grp_fu_16181_p_ce <= ap_const_logic_1;
    grp_fu_16181_p_din0 <= zext_ln133_fu_780_p1;
    grp_fu_16184_p_ce <= ap_const_logic_1;
    grp_fu_16184_p_din0 <= zext_ln135_fu_784_p1;
    grp_fu_16187_p_ce <= ap_const_logic_1;
    grp_fu_16187_p_din0 <= zext_ln132_fu_853_p1;
    grp_fu_2386_p_ce <= ap_const_logic_1;
    grp_fu_2386_p_din0 <= v_reg_1428;
    grp_fu_2386_p_din1 <= conv168_i_reg_1434;
    grp_fu_2390_p_ce <= ap_const_logic_1;
    grp_fu_2390_p_din0 <= v_reg_1428;
    grp_fu_2390_p_din1 <= mn_reg_1423;
    icmp_ln126_fu_636_p2 <= "1" when (ap_sig_allocacmp_n_4 = ap_const_lv9_100) else "0";
    lshr_ln131_fu_738_p2 <= std_logic_vector(shift_right(unsigned(tmp_13_fu_699_p11),to_integer(unsigned('0' & zext_ln131_2_fu_734_p1(8-1 downto 0)))));
    nibble_fu_744_p1 <= lshr_ln131_fu_738_p2(4 - 1 downto 0);
    shl_ln131_5_fu_726_p3 <= (trunc_ln131_fu_723_p1 & ap_const_lv2_0);
    tmp_13_fu_699_p10 <= n_4_reg_1349(2 downto 1);
    tmp_13_fu_699_p9 <= "XXXXXXXX";
    tmp_14_fu_822_p17 <= "XXXXXX";
    tmp_15_fu_748_p17 <= "XXXXXX";
    tmp_15_fu_748_p18 <= n_4_reg_1349(7 downto 5);
    tmp_16_fu_945_p17 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_17_fu_881_p17 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_s_fu_648_p4 <= ap_sig_allocacmp_n_4(7 downto 3);
    trunc_ln129_fu_791_p1 <= n_4_reg_1349_pp0_iter2_reg(3 - 1 downto 0);
    trunc_ln131_fu_723_p1 <= n_4_reg_1349(1 - 1 downto 0);
    zext_ln126_fu_788_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(n_4_reg_1349_pp0_iter2_reg),13));
    zext_ln131_1_fu_668_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln131_fu_662_p2),64));
    zext_ln131_2_fu_734_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln131_5_fu_726_p3),8));
    zext_ln131_fu_658_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_648_p4),6));
    zext_ln132_fu_853_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_14_reg_1418),32));
    zext_ln133_fu_780_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_15_reg_1392),32));
    zext_ln134_fu_799_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln134_fu_794_p2),64));
    zext_ln135_fu_784_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(nibble_reg_1387),32));
end behav;
