-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity swiglu_load_row_down_q4k4 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    W_down : IN STD_LOGIC_VECTOR (7 downto 0);
    rb_0_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    rb_0_ce0 : OUT STD_LOGIC;
    rb_0_we0 : OUT STD_LOGIC;
    rb_0_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    rb_1_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    rb_1_ce0 : OUT STD_LOGIC;
    rb_1_we0 : OUT STD_LOGIC;
    rb_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    rb_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    rb_2_ce0 : OUT STD_LOGIC;
    rb_2_we0 : OUT STD_LOGIC;
    rb_2_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    rb_3_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    rb_3_ce0 : OUT STD_LOGIC;
    rb_3_we0 : OUT STD_LOGIC;
    rb_3_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    rb_4_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    rb_4_ce0 : OUT STD_LOGIC;
    rb_4_we0 : OUT STD_LOGIC;
    rb_4_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    rb_5_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    rb_5_ce0 : OUT STD_LOGIC;
    rb_5_we0 : OUT STD_LOGIC;
    rb_5_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    rb_6_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    rb_6_ce0 : OUT STD_LOGIC;
    rb_6_we0 : OUT STD_LOGIC;
    rb_6_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    rb_7_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    rb_7_ce0 : OUT STD_LOGIC;
    rb_7_we0 : OUT STD_LOGIC;
    rb_7_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    rb_8_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    rb_8_ce0 : OUT STD_LOGIC;
    rb_8_we0 : OUT STD_LOGIC;
    rb_8_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    rb_9_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    rb_9_ce0 : OUT STD_LOGIC;
    rb_9_we0 : OUT STD_LOGIC;
    rb_9_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    rb_10_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    rb_10_ce0 : OUT STD_LOGIC;
    rb_10_we0 : OUT STD_LOGIC;
    rb_10_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    rb_11_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    rb_11_ce0 : OUT STD_LOGIC;
    rb_11_we0 : OUT STD_LOGIC;
    rb_11_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    rb_12_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    rb_12_ce0 : OUT STD_LOGIC;
    rb_12_we0 : OUT STD_LOGIC;
    rb_12_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    rb_13_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    rb_13_ce0 : OUT STD_LOGIC;
    rb_13_we0 : OUT STD_LOGIC;
    rb_13_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    rb_14_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    rb_14_ce0 : OUT STD_LOGIC;
    rb_14_we0 : OUT STD_LOGIC;
    rb_14_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    rb_15_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    rb_15_ce0 : OUT STD_LOGIC;
    rb_15_we0 : OUT STD_LOGIC;
    rb_15_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    rb_16_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    rb_16_ce0 : OUT STD_LOGIC;
    rb_16_we0 : OUT STD_LOGIC;
    rb_16_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    rb_17_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    rb_17_ce0 : OUT STD_LOGIC;
    rb_17_we0 : OUT STD_LOGIC;
    rb_17_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    rb_18_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    rb_18_ce0 : OUT STD_LOGIC;
    rb_18_we0 : OUT STD_LOGIC;
    rb_18_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    rb_19_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    rb_19_ce0 : OUT STD_LOGIC;
    rb_19_we0 : OUT STD_LOGIC;
    rb_19_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    rb_20_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    rb_20_ce0 : OUT STD_LOGIC;
    rb_20_we0 : OUT STD_LOGIC;
    rb_20_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    rb_21_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    rb_21_ce0 : OUT STD_LOGIC;
    rb_21_we0 : OUT STD_LOGIC;
    rb_21_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    rb_22_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    rb_22_ce0 : OUT STD_LOGIC;
    rb_22_we0 : OUT STD_LOGIC;
    rb_22_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    rb_23_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    rb_23_ce0 : OUT STD_LOGIC;
    rb_23_we0 : OUT STD_LOGIC;
    rb_23_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    rb_24_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    rb_24_ce0 : OUT STD_LOGIC;
    rb_24_we0 : OUT STD_LOGIC;
    rb_24_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    rb_25_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    rb_25_ce0 : OUT STD_LOGIC;
    rb_25_we0 : OUT STD_LOGIC;
    rb_25_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    rb_26_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    rb_26_ce0 : OUT STD_LOGIC;
    rb_26_we0 : OUT STD_LOGIC;
    rb_26_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    rb_27_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    rb_27_ce0 : OUT STD_LOGIC;
    rb_27_we0 : OUT STD_LOGIC;
    rb_27_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    rb_28_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    rb_28_ce0 : OUT STD_LOGIC;
    rb_28_we0 : OUT STD_LOGIC;
    rb_28_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    rb_29_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    rb_29_ce0 : OUT STD_LOGIC;
    rb_29_we0 : OUT STD_LOGIC;
    rb_29_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    rb_30_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    rb_30_ce0 : OUT STD_LOGIC;
    rb_30_we0 : OUT STD_LOGIC;
    rb_30_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    rb_31_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    rb_31_ce0 : OUT STD_LOGIC;
    rb_31_we0 : OUT STD_LOGIC;
    rb_31_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of swiglu_load_row_down_q4k4 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv5_1E : STD_LOGIC_VECTOR (4 downto 0) := "11110";
    constant ap_const_lv5_1D : STD_LOGIC_VECTOR (4 downto 0) := "11101";
    constant ap_const_lv5_1C : STD_LOGIC_VECTOR (4 downto 0) := "11100";
    constant ap_const_lv5_1B : STD_LOGIC_VECTOR (4 downto 0) := "11011";
    constant ap_const_lv5_1A : STD_LOGIC_VECTOR (4 downto 0) := "11010";
    constant ap_const_lv5_19 : STD_LOGIC_VECTOR (4 downto 0) := "11001";
    constant ap_const_lv5_18 : STD_LOGIC_VECTOR (4 downto 0) := "11000";
    constant ap_const_lv5_17 : STD_LOGIC_VECTOR (4 downto 0) := "10111";
    constant ap_const_lv5_16 : STD_LOGIC_VECTOR (4 downto 0) := "10110";
    constant ap_const_lv5_15 : STD_LOGIC_VECTOR (4 downto 0) := "10101";
    constant ap_const_lv5_14 : STD_LOGIC_VECTOR (4 downto 0) := "10100";
    constant ap_const_lv5_13 : STD_LOGIC_VECTOR (4 downto 0) := "10011";
    constant ap_const_lv5_12 : STD_LOGIC_VECTOR (4 downto 0) := "10010";
    constant ap_const_lv5_11 : STD_LOGIC_VECTOR (4 downto 0) := "10001";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_F : STD_LOGIC_VECTOR (4 downto 0) := "01111";
    constant ap_const_lv5_E : STD_LOGIC_VECTOR (4 downto 0) := "01110";
    constant ap_const_lv5_D : STD_LOGIC_VECTOR (4 downto 0) := "01101";
    constant ap_const_lv5_C : STD_LOGIC_VECTOR (4 downto 0) := "01100";
    constant ap_const_lv5_B : STD_LOGIC_VECTOR (4 downto 0) := "01011";
    constant ap_const_lv5_A : STD_LOGIC_VECTOR (4 downto 0) := "01010";
    constant ap_const_lv5_9 : STD_LOGIC_VECTOR (4 downto 0) := "01001";
    constant ap_const_lv5_8 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_const_lv5_7 : STD_LOGIC_VECTOR (4 downto 0) := "00111";
    constant ap_const_lv5_6 : STD_LOGIC_VECTOR (4 downto 0) := "00110";
    constant ap_const_lv5_5 : STD_LOGIC_VECTOR (4 downto 0) := "00101";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_const_lv5_3 : STD_LOGIC_VECTOR (4 downto 0) := "00011";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv9_11F : STD_LOGIC_VECTOR (8 downto 0) := "100011111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln314_fu_830_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal icmp_ln315193_reg_642 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln315_fu_818_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_icmp_ln315193_phi_fu_645_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal zext_ln315_fu_704_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal indvar_flatten190_fu_172 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal add_ln314_1_fu_740_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_sig_allocacmp_indvar_flatten190_load : STD_LOGIC_VECTOR (8 downto 0);
    signal b191_fu_176 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal b_fu_692_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_b191_load : STD_LOGIC_VECTOR (5 downto 0);
    signal w192_fu_180 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal w_fu_812_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_w192_load : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln314194_fu_184 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal add_ln314_fu_824_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_add_ln314194_load : STD_LOGIC_VECTOR (5 downto 0);
    signal rb_30_we0_local : STD_LOGIC;
    signal trunc_ln314_fu_700_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal rb_30_ce0_local : STD_LOGIC;
    signal rb_29_we0_local : STD_LOGIC;
    signal rb_29_ce0_local : STD_LOGIC;
    signal rb_28_we0_local : STD_LOGIC;
    signal rb_28_ce0_local : STD_LOGIC;
    signal rb_27_we0_local : STD_LOGIC;
    signal rb_27_ce0_local : STD_LOGIC;
    signal rb_26_we0_local : STD_LOGIC;
    signal rb_26_ce0_local : STD_LOGIC;
    signal rb_25_we0_local : STD_LOGIC;
    signal rb_25_ce0_local : STD_LOGIC;
    signal rb_24_we0_local : STD_LOGIC;
    signal rb_24_ce0_local : STD_LOGIC;
    signal rb_23_we0_local : STD_LOGIC;
    signal rb_23_ce0_local : STD_LOGIC;
    signal rb_22_we0_local : STD_LOGIC;
    signal rb_22_ce0_local : STD_LOGIC;
    signal rb_21_we0_local : STD_LOGIC;
    signal rb_21_ce0_local : STD_LOGIC;
    signal rb_20_we0_local : STD_LOGIC;
    signal rb_20_ce0_local : STD_LOGIC;
    signal rb_19_we0_local : STD_LOGIC;
    signal rb_19_ce0_local : STD_LOGIC;
    signal rb_18_we0_local : STD_LOGIC;
    signal rb_18_ce0_local : STD_LOGIC;
    signal rb_17_we0_local : STD_LOGIC;
    signal rb_17_ce0_local : STD_LOGIC;
    signal rb_16_we0_local : STD_LOGIC;
    signal rb_16_ce0_local : STD_LOGIC;
    signal rb_15_we0_local : STD_LOGIC;
    signal rb_15_ce0_local : STD_LOGIC;
    signal rb_14_we0_local : STD_LOGIC;
    signal rb_14_ce0_local : STD_LOGIC;
    signal rb_13_we0_local : STD_LOGIC;
    signal rb_13_ce0_local : STD_LOGIC;
    signal rb_12_we0_local : STD_LOGIC;
    signal rb_12_ce0_local : STD_LOGIC;
    signal rb_11_we0_local : STD_LOGIC;
    signal rb_11_ce0_local : STD_LOGIC;
    signal rb_10_we0_local : STD_LOGIC;
    signal rb_10_ce0_local : STD_LOGIC;
    signal rb_9_we0_local : STD_LOGIC;
    signal rb_9_ce0_local : STD_LOGIC;
    signal rb_8_we0_local : STD_LOGIC;
    signal rb_8_ce0_local : STD_LOGIC;
    signal rb_7_we0_local : STD_LOGIC;
    signal rb_7_ce0_local : STD_LOGIC;
    signal rb_6_we0_local : STD_LOGIC;
    signal rb_6_ce0_local : STD_LOGIC;
    signal rb_5_we0_local : STD_LOGIC;
    signal rb_5_ce0_local : STD_LOGIC;
    signal rb_4_we0_local : STD_LOGIC;
    signal rb_4_ce0_local : STD_LOGIC;
    signal rb_3_we0_local : STD_LOGIC;
    signal rb_3_ce0_local : STD_LOGIC;
    signal rb_2_we0_local : STD_LOGIC;
    signal rb_2_ce0_local : STD_LOGIC;
    signal rb_1_we0_local : STD_LOGIC;
    signal rb_1_ce0_local : STD_LOGIC;
    signal rb_0_we0_local : STD_LOGIC;
    signal rb_0_ce0_local : STD_LOGIC;
    signal rb_31_we0_local : STD_LOGIC;
    signal rb_31_ce0_local : STD_LOGIC;
    signal select_ln314_fu_684_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component swiglu_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_U : component swiglu_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    add_ln314194_fu_184_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                add_ln314194_fu_184 <= add_ln314_fu_824_p2;
            end if;
        end if;
    end process;

    b191_fu_176_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                b191_fu_176 <= b_fu_692_p3;
            end if;
        end if;
    end process;

    indvar_flatten190_fu_172_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                indvar_flatten190_fu_172 <= add_ln314_1_fu_740_p2;
            end if;
        end if;
    end process;

    w192_fu_180_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                w192_fu_180 <= w_fu_812_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln314_fu_830_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                icmp_ln315193_reg_642 <= icmp_ln315_fu_818_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln314_1_fu_740_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten190_load) + unsigned(ap_const_lv9_1));
    add_ln314_fu_824_p2 <= std_logic_vector(unsigned(b_fu_692_p3) + unsigned(ap_const_lv6_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1_pp0_stage0_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_done_reg, ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_start_int = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln314_fu_830_p2)
    begin
        if (((icmp_ln314_fu_830_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_icmp_ln315193_phi_fu_645_p4_assign_proc : process(ap_CS_fsm_state1, icmp_ln315193_reg_642, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_icmp_ln315193_phi_fu_645_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_icmp_ln315193_phi_fu_645_p4 <= icmp_ln315193_reg_642;
        end if; 
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_add_ln314194_load_assign_proc : process(ap_CS_fsm_state1, ap_loop_init, add_ln314194_fu_184)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_add_ln314194_load <= ap_const_lv6_1;
        else 
            ap_sig_allocacmp_add_ln314194_load <= add_ln314194_fu_184;
        end if; 
    end process;


    ap_sig_allocacmp_b191_load_assign_proc : process(ap_CS_fsm_state1, ap_loop_init, b191_fu_176)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_b191_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_b191_load <= b191_fu_176;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten190_load_assign_proc : process(ap_CS_fsm_state1, ap_loop_init, indvar_flatten190_fu_172)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_indvar_flatten190_load <= ap_const_lv9_0;
        else 
            ap_sig_allocacmp_indvar_flatten190_load <= indvar_flatten190_fu_172;
        end if; 
    end process;


    ap_sig_allocacmp_w192_load_assign_proc : process(ap_CS_fsm_state1, ap_loop_init, w192_fu_180)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_w192_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_w192_load <= w192_fu_180;
        end if; 
    end process;

    b_fu_692_p3 <= 
        ap_sig_allocacmp_add_ln314194_load when (ap_phi_mux_icmp_ln315193_phi_fu_645_p4(0) = '1') else 
        ap_sig_allocacmp_b191_load;
    icmp_ln314_fu_830_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten190_load = ap_const_lv9_11F) else "0";
    icmp_ln315_fu_818_p2 <= "1" when (w_fu_812_p2 = ap_const_lv4_9) else "0";
    rb_0_address0 <= zext_ln315_fu_704_p1(4 - 1 downto 0);
    rb_0_ce0 <= rb_0_ce0_local;

    rb_0_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_0_ce0_local <= ap_const_logic_1;
        else 
            rb_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_0_d0 <= W_down;
    rb_0_we0 <= rb_0_we0_local;

    rb_0_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, trunc_ln314_fu_700_p1)
    begin
        if (((trunc_ln314_fu_700_p1 = ap_const_lv5_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_0_we0_local <= ap_const_logic_1;
        else 
            rb_0_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_10_address0 <= zext_ln315_fu_704_p1(4 - 1 downto 0);
    rb_10_ce0 <= rb_10_ce0_local;

    rb_10_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_10_ce0_local <= ap_const_logic_1;
        else 
            rb_10_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_10_d0 <= W_down;
    rb_10_we0 <= rb_10_we0_local;

    rb_10_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, trunc_ln314_fu_700_p1)
    begin
        if (((trunc_ln314_fu_700_p1 = ap_const_lv5_A) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_10_we0_local <= ap_const_logic_1;
        else 
            rb_10_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_11_address0 <= zext_ln315_fu_704_p1(4 - 1 downto 0);
    rb_11_ce0 <= rb_11_ce0_local;

    rb_11_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_11_ce0_local <= ap_const_logic_1;
        else 
            rb_11_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_11_d0 <= W_down;
    rb_11_we0 <= rb_11_we0_local;

    rb_11_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, trunc_ln314_fu_700_p1)
    begin
        if (((trunc_ln314_fu_700_p1 = ap_const_lv5_B) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_11_we0_local <= ap_const_logic_1;
        else 
            rb_11_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_12_address0 <= zext_ln315_fu_704_p1(4 - 1 downto 0);
    rb_12_ce0 <= rb_12_ce0_local;

    rb_12_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_12_ce0_local <= ap_const_logic_1;
        else 
            rb_12_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_12_d0 <= W_down;
    rb_12_we0 <= rb_12_we0_local;

    rb_12_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, trunc_ln314_fu_700_p1)
    begin
        if (((trunc_ln314_fu_700_p1 = ap_const_lv5_C) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_12_we0_local <= ap_const_logic_1;
        else 
            rb_12_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_13_address0 <= zext_ln315_fu_704_p1(4 - 1 downto 0);
    rb_13_ce0 <= rb_13_ce0_local;

    rb_13_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_13_ce0_local <= ap_const_logic_1;
        else 
            rb_13_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_13_d0 <= W_down;
    rb_13_we0 <= rb_13_we0_local;

    rb_13_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, trunc_ln314_fu_700_p1)
    begin
        if (((trunc_ln314_fu_700_p1 = ap_const_lv5_D) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_13_we0_local <= ap_const_logic_1;
        else 
            rb_13_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_14_address0 <= zext_ln315_fu_704_p1(4 - 1 downto 0);
    rb_14_ce0 <= rb_14_ce0_local;

    rb_14_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_14_ce0_local <= ap_const_logic_1;
        else 
            rb_14_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_14_d0 <= W_down;
    rb_14_we0 <= rb_14_we0_local;

    rb_14_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, trunc_ln314_fu_700_p1)
    begin
        if (((trunc_ln314_fu_700_p1 = ap_const_lv5_E) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_14_we0_local <= ap_const_logic_1;
        else 
            rb_14_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_15_address0 <= zext_ln315_fu_704_p1(4 - 1 downto 0);
    rb_15_ce0 <= rb_15_ce0_local;

    rb_15_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_15_ce0_local <= ap_const_logic_1;
        else 
            rb_15_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_15_d0 <= W_down;
    rb_15_we0 <= rb_15_we0_local;

    rb_15_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, trunc_ln314_fu_700_p1)
    begin
        if (((trunc_ln314_fu_700_p1 = ap_const_lv5_F) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_15_we0_local <= ap_const_logic_1;
        else 
            rb_15_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_16_address0 <= zext_ln315_fu_704_p1(4 - 1 downto 0);
    rb_16_ce0 <= rb_16_ce0_local;

    rb_16_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_16_ce0_local <= ap_const_logic_1;
        else 
            rb_16_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_16_d0 <= W_down;
    rb_16_we0 <= rb_16_we0_local;

    rb_16_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, trunc_ln314_fu_700_p1)
    begin
        if (((trunc_ln314_fu_700_p1 = ap_const_lv5_10) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_16_we0_local <= ap_const_logic_1;
        else 
            rb_16_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_17_address0 <= zext_ln315_fu_704_p1(4 - 1 downto 0);
    rb_17_ce0 <= rb_17_ce0_local;

    rb_17_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_17_ce0_local <= ap_const_logic_1;
        else 
            rb_17_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_17_d0 <= W_down;
    rb_17_we0 <= rb_17_we0_local;

    rb_17_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, trunc_ln314_fu_700_p1)
    begin
        if (((trunc_ln314_fu_700_p1 = ap_const_lv5_11) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_17_we0_local <= ap_const_logic_1;
        else 
            rb_17_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_18_address0 <= zext_ln315_fu_704_p1(4 - 1 downto 0);
    rb_18_ce0 <= rb_18_ce0_local;

    rb_18_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_18_ce0_local <= ap_const_logic_1;
        else 
            rb_18_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_18_d0 <= W_down;
    rb_18_we0 <= rb_18_we0_local;

    rb_18_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, trunc_ln314_fu_700_p1)
    begin
        if (((trunc_ln314_fu_700_p1 = ap_const_lv5_12) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_18_we0_local <= ap_const_logic_1;
        else 
            rb_18_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_19_address0 <= zext_ln315_fu_704_p1(4 - 1 downto 0);
    rb_19_ce0 <= rb_19_ce0_local;

    rb_19_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_19_ce0_local <= ap_const_logic_1;
        else 
            rb_19_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_19_d0 <= W_down;
    rb_19_we0 <= rb_19_we0_local;

    rb_19_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, trunc_ln314_fu_700_p1)
    begin
        if (((trunc_ln314_fu_700_p1 = ap_const_lv5_13) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_19_we0_local <= ap_const_logic_1;
        else 
            rb_19_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_1_address0 <= zext_ln315_fu_704_p1(4 - 1 downto 0);
    rb_1_ce0 <= rb_1_ce0_local;

    rb_1_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_1_ce0_local <= ap_const_logic_1;
        else 
            rb_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_1_d0 <= W_down;
    rb_1_we0 <= rb_1_we0_local;

    rb_1_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, trunc_ln314_fu_700_p1)
    begin
        if (((trunc_ln314_fu_700_p1 = ap_const_lv5_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_1_we0_local <= ap_const_logic_1;
        else 
            rb_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_20_address0 <= zext_ln315_fu_704_p1(4 - 1 downto 0);
    rb_20_ce0 <= rb_20_ce0_local;

    rb_20_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_20_ce0_local <= ap_const_logic_1;
        else 
            rb_20_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_20_d0 <= W_down;
    rb_20_we0 <= rb_20_we0_local;

    rb_20_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, trunc_ln314_fu_700_p1)
    begin
        if (((trunc_ln314_fu_700_p1 = ap_const_lv5_14) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_20_we0_local <= ap_const_logic_1;
        else 
            rb_20_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_21_address0 <= zext_ln315_fu_704_p1(4 - 1 downto 0);
    rb_21_ce0 <= rb_21_ce0_local;

    rb_21_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_21_ce0_local <= ap_const_logic_1;
        else 
            rb_21_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_21_d0 <= W_down;
    rb_21_we0 <= rb_21_we0_local;

    rb_21_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, trunc_ln314_fu_700_p1)
    begin
        if (((trunc_ln314_fu_700_p1 = ap_const_lv5_15) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_21_we0_local <= ap_const_logic_1;
        else 
            rb_21_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_22_address0 <= zext_ln315_fu_704_p1(4 - 1 downto 0);
    rb_22_ce0 <= rb_22_ce0_local;

    rb_22_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_22_ce0_local <= ap_const_logic_1;
        else 
            rb_22_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_22_d0 <= W_down;
    rb_22_we0 <= rb_22_we0_local;

    rb_22_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, trunc_ln314_fu_700_p1)
    begin
        if (((trunc_ln314_fu_700_p1 = ap_const_lv5_16) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_22_we0_local <= ap_const_logic_1;
        else 
            rb_22_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_23_address0 <= zext_ln315_fu_704_p1(4 - 1 downto 0);
    rb_23_ce0 <= rb_23_ce0_local;

    rb_23_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_23_ce0_local <= ap_const_logic_1;
        else 
            rb_23_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_23_d0 <= W_down;
    rb_23_we0 <= rb_23_we0_local;

    rb_23_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, trunc_ln314_fu_700_p1)
    begin
        if (((trunc_ln314_fu_700_p1 = ap_const_lv5_17) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_23_we0_local <= ap_const_logic_1;
        else 
            rb_23_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_24_address0 <= zext_ln315_fu_704_p1(4 - 1 downto 0);
    rb_24_ce0 <= rb_24_ce0_local;

    rb_24_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_24_ce0_local <= ap_const_logic_1;
        else 
            rb_24_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_24_d0 <= W_down;
    rb_24_we0 <= rb_24_we0_local;

    rb_24_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, trunc_ln314_fu_700_p1)
    begin
        if (((trunc_ln314_fu_700_p1 = ap_const_lv5_18) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_24_we0_local <= ap_const_logic_1;
        else 
            rb_24_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_25_address0 <= zext_ln315_fu_704_p1(4 - 1 downto 0);
    rb_25_ce0 <= rb_25_ce0_local;

    rb_25_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_25_ce0_local <= ap_const_logic_1;
        else 
            rb_25_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_25_d0 <= W_down;
    rb_25_we0 <= rb_25_we0_local;

    rb_25_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, trunc_ln314_fu_700_p1)
    begin
        if (((trunc_ln314_fu_700_p1 = ap_const_lv5_19) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_25_we0_local <= ap_const_logic_1;
        else 
            rb_25_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_26_address0 <= zext_ln315_fu_704_p1(4 - 1 downto 0);
    rb_26_ce0 <= rb_26_ce0_local;

    rb_26_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_26_ce0_local <= ap_const_logic_1;
        else 
            rb_26_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_26_d0 <= W_down;
    rb_26_we0 <= rb_26_we0_local;

    rb_26_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, trunc_ln314_fu_700_p1)
    begin
        if (((trunc_ln314_fu_700_p1 = ap_const_lv5_1A) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_26_we0_local <= ap_const_logic_1;
        else 
            rb_26_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_27_address0 <= zext_ln315_fu_704_p1(4 - 1 downto 0);
    rb_27_ce0 <= rb_27_ce0_local;

    rb_27_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_27_ce0_local <= ap_const_logic_1;
        else 
            rb_27_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_27_d0 <= W_down;
    rb_27_we0 <= rb_27_we0_local;

    rb_27_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, trunc_ln314_fu_700_p1)
    begin
        if (((trunc_ln314_fu_700_p1 = ap_const_lv5_1B) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_27_we0_local <= ap_const_logic_1;
        else 
            rb_27_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_28_address0 <= zext_ln315_fu_704_p1(4 - 1 downto 0);
    rb_28_ce0 <= rb_28_ce0_local;

    rb_28_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_28_ce0_local <= ap_const_logic_1;
        else 
            rb_28_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_28_d0 <= W_down;
    rb_28_we0 <= rb_28_we0_local;

    rb_28_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, trunc_ln314_fu_700_p1)
    begin
        if (((trunc_ln314_fu_700_p1 = ap_const_lv5_1C) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_28_we0_local <= ap_const_logic_1;
        else 
            rb_28_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_29_address0 <= zext_ln315_fu_704_p1(4 - 1 downto 0);
    rb_29_ce0 <= rb_29_ce0_local;

    rb_29_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_29_ce0_local <= ap_const_logic_1;
        else 
            rb_29_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_29_d0 <= W_down;
    rb_29_we0 <= rb_29_we0_local;

    rb_29_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, trunc_ln314_fu_700_p1)
    begin
        if (((trunc_ln314_fu_700_p1 = ap_const_lv5_1D) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_29_we0_local <= ap_const_logic_1;
        else 
            rb_29_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_2_address0 <= zext_ln315_fu_704_p1(4 - 1 downto 0);
    rb_2_ce0 <= rb_2_ce0_local;

    rb_2_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_2_ce0_local <= ap_const_logic_1;
        else 
            rb_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_2_d0 <= W_down;
    rb_2_we0 <= rb_2_we0_local;

    rb_2_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, trunc_ln314_fu_700_p1)
    begin
        if (((trunc_ln314_fu_700_p1 = ap_const_lv5_2) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_2_we0_local <= ap_const_logic_1;
        else 
            rb_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_30_address0 <= zext_ln315_fu_704_p1(4 - 1 downto 0);
    rb_30_ce0 <= rb_30_ce0_local;

    rb_30_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_30_ce0_local <= ap_const_logic_1;
        else 
            rb_30_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_30_d0 <= W_down;
    rb_30_we0 <= rb_30_we0_local;

    rb_30_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, trunc_ln314_fu_700_p1)
    begin
        if (((trunc_ln314_fu_700_p1 = ap_const_lv5_1E) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_30_we0_local <= ap_const_logic_1;
        else 
            rb_30_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_31_address0 <= zext_ln315_fu_704_p1(4 - 1 downto 0);
    rb_31_ce0 <= rb_31_ce0_local;

    rb_31_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_31_ce0_local <= ap_const_logic_1;
        else 
            rb_31_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_31_d0 <= W_down;
    rb_31_we0 <= rb_31_we0_local;

    rb_31_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, trunc_ln314_fu_700_p1)
    begin
        if (((trunc_ln314_fu_700_p1 = ap_const_lv5_1F) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_31_we0_local <= ap_const_logic_1;
        else 
            rb_31_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_3_address0 <= zext_ln315_fu_704_p1(4 - 1 downto 0);
    rb_3_ce0 <= rb_3_ce0_local;

    rb_3_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_3_ce0_local <= ap_const_logic_1;
        else 
            rb_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_3_d0 <= W_down;
    rb_3_we0 <= rb_3_we0_local;

    rb_3_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, trunc_ln314_fu_700_p1)
    begin
        if (((trunc_ln314_fu_700_p1 = ap_const_lv5_3) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_3_we0_local <= ap_const_logic_1;
        else 
            rb_3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_4_address0 <= zext_ln315_fu_704_p1(4 - 1 downto 0);
    rb_4_ce0 <= rb_4_ce0_local;

    rb_4_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_4_ce0_local <= ap_const_logic_1;
        else 
            rb_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_4_d0 <= W_down;
    rb_4_we0 <= rb_4_we0_local;

    rb_4_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, trunc_ln314_fu_700_p1)
    begin
        if (((trunc_ln314_fu_700_p1 = ap_const_lv5_4) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_4_we0_local <= ap_const_logic_1;
        else 
            rb_4_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_5_address0 <= zext_ln315_fu_704_p1(4 - 1 downto 0);
    rb_5_ce0 <= rb_5_ce0_local;

    rb_5_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_5_ce0_local <= ap_const_logic_1;
        else 
            rb_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_5_d0 <= W_down;
    rb_5_we0 <= rb_5_we0_local;

    rb_5_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, trunc_ln314_fu_700_p1)
    begin
        if (((trunc_ln314_fu_700_p1 = ap_const_lv5_5) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_5_we0_local <= ap_const_logic_1;
        else 
            rb_5_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_6_address0 <= zext_ln315_fu_704_p1(4 - 1 downto 0);
    rb_6_ce0 <= rb_6_ce0_local;

    rb_6_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_6_ce0_local <= ap_const_logic_1;
        else 
            rb_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_6_d0 <= W_down;
    rb_6_we0 <= rb_6_we0_local;

    rb_6_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, trunc_ln314_fu_700_p1)
    begin
        if (((trunc_ln314_fu_700_p1 = ap_const_lv5_6) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_6_we0_local <= ap_const_logic_1;
        else 
            rb_6_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_7_address0 <= zext_ln315_fu_704_p1(4 - 1 downto 0);
    rb_7_ce0 <= rb_7_ce0_local;

    rb_7_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_7_ce0_local <= ap_const_logic_1;
        else 
            rb_7_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_7_d0 <= W_down;
    rb_7_we0 <= rb_7_we0_local;

    rb_7_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, trunc_ln314_fu_700_p1)
    begin
        if (((trunc_ln314_fu_700_p1 = ap_const_lv5_7) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_7_we0_local <= ap_const_logic_1;
        else 
            rb_7_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_8_address0 <= zext_ln315_fu_704_p1(4 - 1 downto 0);
    rb_8_ce0 <= rb_8_ce0_local;

    rb_8_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_8_ce0_local <= ap_const_logic_1;
        else 
            rb_8_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_8_d0 <= W_down;
    rb_8_we0 <= rb_8_we0_local;

    rb_8_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, trunc_ln314_fu_700_p1)
    begin
        if (((trunc_ln314_fu_700_p1 = ap_const_lv5_8) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_8_we0_local <= ap_const_logic_1;
        else 
            rb_8_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_9_address0 <= zext_ln315_fu_704_p1(4 - 1 downto 0);
    rb_9_ce0 <= rb_9_ce0_local;

    rb_9_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_9_ce0_local <= ap_const_logic_1;
        else 
            rb_9_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    rb_9_d0 <= W_down;
    rb_9_we0 <= rb_9_we0_local;

    rb_9_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, trunc_ln314_fu_700_p1)
    begin
        if (((trunc_ln314_fu_700_p1 = ap_const_lv5_9) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rb_9_we0_local <= ap_const_logic_1;
        else 
            rb_9_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln314_fu_684_p3 <= 
        ap_const_lv4_0 when (ap_phi_mux_icmp_ln315193_phi_fu_645_p4(0) = '1') else 
        ap_sig_allocacmp_w192_load;
    trunc_ln314_fu_700_p1 <= b_fu_692_p3(5 - 1 downto 0);
    w_fu_812_p2 <= std_logic_vector(unsigned(select_ln314_fu_684_p3) + unsigned(ap_const_lv4_1));
    zext_ln315_fu_704_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln314_fu_684_p3),64));
end behav;
